### ISSUE TITLE
[Bug][Compiler-v2] implicit copy of mutable reference

### ISSUE THREAD

**Issue by rahxephon89** [aptos-labs/aptos-core#11117]
# 🐛 Bug

When compiling the `smart_table.move`, the following code snippet:

```
        let old_bucket = table_with_length::borrow_mut(&mut table.buckets, to_split);
        // partition the bucket, [0..p) stays in old bucket, [p..len) goes to new bucket
        let p = vector::partition(old_bucket, |e| {
            let entry: &Entry<K, V> = e; // Explicit type to satisfy compiler
            bucket_index(table.level, table.num_buckets, entry.hash) != new_bucket_index
        });
        let new_bucket = vector::trim_reverse(old_bucket, p);
```

leads the error: 

```
error: implicit copy of mutable reference in local `old_bucket` which is used later
    ┌─ /Users/tengzhang/aptos-core/aptos-move/framework/aptos-stdlib/../move-stdlib/sources/vector.move:473:5
    │  
473 │ ╭     public inline fun partition<Element>(
474 │ │         v: &mut vector<Element>,
475 │ │         pred: |&Element|bool
476 │ │     ): u64 {
    · │
492 │ │         p
493 │ │     }
    │ ╰─────^ implicitly copied here
    │  
    ┌─ /Users/tengzhang/aptos-core/aptos-move/framework/aptos-stdlib/sources/data_structures/smart_table.move:199:26
    │
199 │         let new_bucket = vector::trim_reverse(old_bucket, p);
    │                          ----------------------------------- used here

```

Not sure whether it is a bug of reference checking or inline function. cc @wrwg @brianrmurphy

**Comment by wrwg** [comment]
This problem is a bit more fundamental as I first thought. I created PR #11118 to illustrated the problem. This contains in `mut_inline.move` the minimized repro. The situation here is that we are passing in a local of type `&mut T` into an inline function. However, this now leads to a copy because the local is used afterwards:

```
let r = &mut v;
inlined_function(r);
~~r~~
```

... is expanded to:

```
let r = &mut v;
{ let param = r; <body> };
~~r~~
```

The compiler thinks that `r` needs to be copied because its used afterwards. Notice that the specific v1 semantics for references would have allowed this, but in v2 mutable references cannot be copied. 

In fact that v2 semantics here is that mut-ref is transferred in and out of a function call. For inlining, this would mean generate code like below:

```
let r = &mut v;
{ let param = r; <body>;
   r = param; // give back to r
};
~~r~~
```

**Comment by vineethk** [comment]
FWIW, this is the simplified test case I got to last night, which happens to demonstrate what @wrwg mentioned above:

```
//# publish
module 0x42::m {
    inline fun apply_twice(f: |&mut u64|, x: &mut u64) {
        f(x);
        f(x);
    }

    public fun stuff() {
        let a = 1;
        apply_twice(|x| {
            *x = *freeze(x) + 1;
        }, &mut a);
    }
}

//# run 0x42::m::stuff

```

This transactional test runs fine in v1, but fails with the above mentioned problem in v2.

**Comment by brmataptos** [comment]
Several additional problems discussed:
- `r` must be treated as a free variable in the scope, to assign it at end of function
- lambda parameter could use `r `as a free variable.  will this be a problem for borrow semantics?
- for the update to `r` at end of the function, need to avoid warnings/errors in liveness analysis in case it isn't used.
