### ISSUE TITLE
[Bug][Compiler-v2] Name conflicts between local variables and built-in functions

### ISSUE THREAD

**Issue by rahxephon89** [aptos-labs/aptos-core#11737]
# 🐛 Bug

`len` is a built-in function used in the specification. When compiling the following code:

```
    fun f(gallery: &vector<u64>) {
        let len = 5;
        spec {
            assert len(gallery) >= 0;
        };
    }
```

The following error will be generated:

```
- error: expected `|vector<u64>|?0` but found `u64`
-   ┌─ tests/checking/specs/len.move:5:20
-   │
- 5 │             assert len(gallery) >= 0;
```

**Comment by wrwg** [comment]
Actually I think this error is correct. Local variable shadows global builtin function, not the other way around

**Comment by rahxephon89** [comment]
> Actually I think this error is correct. Local variable shadows global builtin function, not the other way around

I have two concerns: 1) it is not consistent with the V1 behavior; 2) for the following function, both V1 and V2 can compile it. I am confused: does the function f shadow over the local variable f?

```
    fun f(): u64 {
        0
    }

    fun foo() {
        let f = 5;
        spec {
            assert f() == 0;
        };
    }
```

**Comment by brmataptos** [comment]
Are these builtin functions only used in `spec` code?  I suggest we list them somewhere in docs (not just in move-model/src/builder/builtins.rs).

What happens if the user defines a function called `len` and it's used in a `spec` clause?  Does the user declaration shadow the builtin in that case?

The rule of least surprise suggests that we should be as consistent as possible.  The rules for user-defined functions and var declarations suggest that there are 2 separate namespaces, so we should do the same for built-in functions vs var declarations.  But user-defined functions should shadow built-in functions or should yield an error (and we should document the builtin functions).

**Comment by rahxephon89** [comment]
> Are these builtin functions only used in `spec` code? I suggest we list them somewhere in docs (not just in move-model/src/builder/builtins.rs).
> 
> What happens if the user defines a function called `len` and it's used in a `spec` clause? Does the user declaration shadow the builtin in that case?
> 
> The rule of least surprise suggests that we should be as consistent as possible. The rules for user-defined functions and var declarations suggest that there are 2 separate namespaces, so we should do the same for built-in functions vs var declarations. But user-defined functions should shadow built-in functions or should yield an error (and we should document the builtin functions).

1) Yes, they are only used in specs;
2) In both V1 and V2, if there is user-defined function `len`, it will shadow over the built-in one.

**Comment by rahxephon89** [comment]
> Are these builtin functions only used in `spec` code? I suggest we list them somewhere in docs (not just in move-model/src/builder/builtins.rs).

Hi @brianrmurphy , we have listed all built-in functions in the [specification language doc](https://aptos.dev/move/prover/spec-lang#built-in-functions).
