### ISSUE TITLE
[Bug][Docs] inline function docs bugs, reference parameters/results

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#12043]
# 🐛 Bug

https://aptos.dev/move/book/functions#inline-functions says
```
- Inline functions and lambda expressions cannot have `return`, `break`, or `continue` expressions.
```
which is not quite true.  They can have `break` or `continue` expressions that occur inside a loop.  This could perhaps be described concisely as they "cannot have `return` expressions, or *free* `break` or `continue` expressions (occuring outside of a loop)".

While we're touching this file, we also add a section discussing the fact that inline functions allow certain sorts of reference borrowing that is impossible in normal functions.  In particular, we could say something like:

> As borrow checking happens after inline functions are expanded at call sites, they are able to use references in parameters and results in a way which is not possible in normal functions, and may provide additional capabilities to programs.  For example, actual arguments to a call to a non-`inline` function may not be aliased unsafely (multiple `&` parameters referring to the same object, with at least one of them `&mut`) but calls to `inline` functions do not necessarily have that restriction (it depends on the underlying code).  A reference-typed value returned from a non-`inline` function must be derived from a reference parameter passed to the function, but this need not be the case for an `inline` function.
> 
> For this reason, documentation of an `inline` function should carefully document any underlying restrictions on paramter aliasing.

Ideally, there would be a documentation of these reference parameter restrictions on non-`inline` functions somewhere else in the docs, but I can't find it.

**Comment by brmataptos** [comment]
@wrwg @vineethk maybe you can double-check my wording and know if there is existing documentation of the borrow semantics around non-inline function parameters that could be cited?

**Comment by vineethk** [comment]
> This could perhaps be described concisely as they "cannot have return expressions, or free break or continue expressions (occuring outside of a loop)".

Sounds reasonable to me.

> A reference-typed value returned from a non-inline function must be derived from a reference parameter passed to the function, but this need not be the case for an inline function.

Note that this is already documented (along with an additional usecase) as a "tip" under the earlier section return type. If we want to duplicate this information (which is okay), then we could prefix it with "As described in a tip above (with link?), .."

> For this reason, documentation of an inline function should carefully document any underlying restrictions on paramter aliasing.

Could we mention this as a best practice rather than "should"? Also "paramter" => "parameter".

The writeup is nice, although, it may be a bit dense for a general reader (eg., I am not sure if borrow checker is something that has been discussed before, and it might be good to have a whole section on that?). We could go with this for now (as it better than having no information - interested/diligent readers have something to refer to).
