### ISSUE TITLE
[Bug]Modulo precision with large numbers

### ISSUE THREAD

**Issue by dantheman8300** [aptos-labs/aptos-core#12426]
# 🐛 Bug

I am running into an issue when using the modulo operator (%) on large numbers. I get incorrect results. 

## To reproduce

**Code snippet**
<img width="879" alt="Screenshot_2024-03-06_at_12 23 10_PM" src="https://github.com/aptos-labs/aptos-core/assets/71237296/f3ed4dfb-6d59-4138-a660-78660095e0e7">

**Stack trace/error message**
<img width="638" alt="Screenshot_2024-03-06_at_12 23 17_PM" src="https://github.com/aptos-labs/aptos-core/assets/71237296/0be49328-7db4-4194-aa20-e55971e8bf78">

## Expected Behavior
<img width="900" alt="Screenshot_2024-03-06_at_12 24 30_PM" src="https://github.com/aptos-labs/aptos-core/assets/71237296/79e62592-91b6-4344-ab0b-369b3801c5c7">

I expect the answer to be 15 like it is with this online modulo operator.

## System information

**Please complete the following information:**
- aptos 2.5.0
- rustc 1.72.1 (d5c2e9c34 2023-09-13)
- Mac OS (M1)

## Additional context

The modulo operator seems to work fine with smaller numbers, but this happens when I am dealing with larger numbers.

**Comment by vgao1996** [comment]
I've attempted this division through a few different methods and they all agree on 30 as the result.
- Rust Playground (num_bigint)
  - https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9563ff3449f3dd88f566634d4a9b675b
- Wolframalpha
  - https://www.wolframalpha.com/input?i=9969647506454130227674018047161338038021863940491555036153395554133127286501+%25+33
- ChatGPT
  - <img width="801" alt="Screenshot 2024-03-07 at 3 11 15 PM" src="https://github.com/aptos-labs/aptos-core/assets/10379359/bf305347-8f59-47c4-83b8-b9e55e020d1c">

Looks like the bug is in the Modulo Calculator for Large Numbers you are using?

**Comment by vgao1996** [comment]
<img width="790" alt="Screenshot 2024-03-07 at 3 25 03 PM" src="https://github.com/aptos-labs/aptos-core/assets/10379359/e86b5e94-a7b8-4f3c-b91a-00e17856b2e2">
Yeah, that tool is obviously buggy for large numbers

**Comment by vgao1996** [comment]
```
function calculate()
{
document.getElementById("show").style.display = "block";
var aa =  document.getElementById("a1").value;
var bb = document.getElementById("b1").value;
if(aa=="" || bb=="")
{
alert("Enter the inputs");
}
else
{
var res=aa%bb;
var z = document.getElementById("results");
z.innerHTML = "<table><thead><tr><th>Result</th></tr></thead><tbody><tr><td>" + aa  + " MOD " + bb + " is :<b>" + " " + res + "</b></td></tr></tbody></table>";
}
}
```
Here's the javascript code from the online modulo calculator. It stores the integers as IEEE 754 doubles. The biggest integer this data type can safely represent is roughly 2^53. They should have used big ints for this kind of calculation.

**Comment by dantheman8300** [comment]
I see, thanks for taking a look for me! In hindsight, should have check more than one source haha. Was the towards the end of my late night coding sesh. Thanks! I'll go ahead and close this
