### ISSUE TITLE
[Bug][move-compiler-v2] TS SDK E2E tests broken

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#12544]
# 🐛 Bug

For example see
https://github.com/aptos-labs/aptos-core/actions/runs/8289346019/job/22685614921?pr=12518

It looks like some compiler path has changed and aptos flags aren't being properly propagated, so known_attributes is broken.

**Comment by brmataptos** [comment]
I see it as early as Jan 24, 8:01pm in my PR #18161, but it may have happened earlier.

**Comment by wrwg** [comment]
The TS SDK tests have been failing since months and the v2 compiler is not involved in them. In general, without the env var `MOVE_COMPILER_V2=true`, the v2 compiler will not be involved in any existing code. Currently we set this var only in the dedicated Move compiler v2 github action.

**Comment by brmataptos** [comment]
That's great, you fixed the TS SDK tests, @wrwg ?

No.

**Comment by brmataptos** [comment]
Sent back for Triaging.  This really should go to whoever owns TS SDK.  It is not compiler-v2 related.

**Comment by wrwg** [comment]
You tagged this as a Move bug and it appeared as urgent in the compiler-v2 dashboard. Feel free to reopen the bug and assign to the TS SDK team, which is completely unrelated to the Move team. I recommend to talk with Greg first whether they have any intention to fix, I think they do not because there is a new version of the TS SDK again.

Closing again.
