### ISSUE TITLE
[Bug][move-compiler-v2] prover output degradation

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#12649]
# 🐛 Bug

With PR#12637, we see that test output third_party/move/move-prover/tests/sources/regression/type_param_bug_200228.v2_exp seems to have a redundant reference to line 6.    May be worth looking into.

**Comment by wrwg** [comment]
This is actually not a stack trace but an execution trace (i.e. the sequence of steps in the program execution leading to the verification failure). With slight changes in the bytecode this can change, and an entry without any variables is possible, because which variables are printed in each step is based on some heuristics of what state has changed. The entire logic around producing this kind of execution trace is super complex piece of code in the prover as the SMT counter example is indeed completely different than the original program. So this is kind of expected. Thanks for flagging, but unless you want to discuss more, I suggest to close.

**Comment by brmataptos** [comment]
Ok, sounds good.
