### ISSUE TITLE
[Feature Request] Fetch signed block header (`LedgerInfoWithSignatures`) for any arbitrary block height in a PFN

### ISSUE THREAD

**Issue by wwared** [aptos-labs/aptos-core#13440]
## Prior refs

This issue is motivated by the development of a self-contained light client for Aptos ([context](https://wormhole.foundation/blog/wormhole-foundation-awards-contributor-grant-to-lurk-lab-to-bring-trustless-transfers-to-wormhole-with-zk-proofs)), and some previous issues discussing this are #11824, #10747 and #7401.

## Motivation

This issue refers specifically to the need of a light client to fetch a signed Block Header for the block height it wants to generate a Merkle proof of inclusion of some value. It's necessary to not only generate a `SparseMerkleProof` for an arbitrary version, but also fetch the corresponding `LedgerInfoWithSignatures` for that specific version so the light client can verify the provenance of the state root Merkle hash used in the `SparseMerkleProof`.

## Our exploration

Looking through the AptosDB schema files, we've identified the following places that store `LedgerInfoWithSignatures` directly for easy retrieval, however none of them seem sufficient for this:

* The [`ledger_info`](https://github.com/aptos-labs/aptos-core/blob/main/storage/aptosdb/src/schema/ledger_info/mod.rs) schema uses Epoch numbers to key specific `LedgerInfoWithSchema` values, keeping one per epoch (the most recent, I believe, up to the last block in the epoch), so this is not able to give us the `LedgerInfoWithSignatures` for a specific version or height
* The [`block_by_version`](https://github.com/aptos-labs/aptos-core/blob/main/storage/aptosdb/src/schema/block_by_version/mod.rs) and [`block_info`](https://github.com/aptos-labs/aptos-core/blob/main/storage/aptosdb/src/schema/block_info/mod.rs) schemas lets us find the corresponding block height for a version as well as the [`BlockInfo`](https://github.com/aptos-labs/aptos-core/blob/main/types/src/block_info.rs) struct for any arbitrary block height, but the `BlockInfo` struct does not contain any signature data, so it is not sufficient by itself
* The methods in the `DbReader` trait (implemented in [`aptosdb_reader`](https://github.com/aptos-labs/aptos-core/blob/main/storage/aptosdb/src/db/include/aptosdb_reader.rs)) don't have any methods that lets us get the `LedgerInfoWithSignatures` for a specific block height or version, since these methods focus on either getting the latest/most recent `LedgerInfoWithSignatures` (`get_latest_ledger_info_option`), or getting the `StateProof` containing both a `LedgerInfoWithSignatures` and an `EpochChangeProof` for a specific version (`get_epoch_ending_ledger_info` and `get_state_proof_with_ledger_info`). It doesn't seem like any methods let us query for arbitrary `LedgerInfoWithSignatures` for any arbitrary block
* There exists the Quorum Store DB, and its [`quorum_certificate`](https://github.com/aptos-labs/aptos-core/blob/main/consensus/src/consensusdb/schema/quorum_certificate/mod.rs) schema allows us to map a block hash to a [`QuorumCert`](https://github.com/aptos-labs/aptos-core/blob/main/consensus/consensus-types/src/quorum_cert.rs) struct, which does contain the `LedgerInfoWithSignatures`! However: the Quorum Store DB does not seem to be available on every regular Public Full Node, only Validators, so querying this DB does not seem to be the correct choice (here is the [initialization code](https://github.com/aptos-labs/aptos-core/blob/415d7e12e94ebd833a910ed4138742f005149610/aptos-node/src/lib.rs#L792-L802) that only starts the corresponding services for Validators). I've also attempted dumping both the Consensus DB and the Quorum Store DB via the [admin interface debug endpoints](https://github.com/aptos-labs/aptos-core/blob/415d7e12e94ebd833a910ed4138742f005149610/crates/aptos-admin-service/src/server/mod.rs#L174-L195), but for my non-validator full node those returned an error saying the DB was unavailable
  * There seems to be a new in-development "consensus observer" feature that seems to enable some (or both) of the Consensus DB and Quorum Store DB for PFNs that enable it in the config, but it's unclear to me if this feature is meant to support this usecase or something else

## Next steps

I wasn't able to find any direct and intended way of retrieving signed block headers for arbitrary blocks witnessed by a full node. Is there something I'm missing in regards to how this data is stored in the node's DB, or some other way of fetching historical `LedgerInfoWithSignatures` data for any arbitrary block height? If not, could support for this be added?

I understand that for most cases, the node only needs to keep track of `LedgerInfoWithSignatures` that are necessary for processing Epoch changes, as well as its most recent value, but I presume that since the full node ends up witnessing all of the `LedgerInfoWithSignatures` during the process of keeping up with the network, that this data would be stored somewhere and could be retrieved in some way.

**Comment by msmouse** [comment]
@wwared  amazing job digging into the code to find out about our data structure. I now owe you detailed documentation on that topic. But before I deliver, refer to this: (we are very much still on a similar construction) https://github.com/msmouse/diem/blob/main/specifications/common/authenticated_data_structures.md

That aside, 
>  It's necessary to not only generate a `SparseMerkleProof` for an arbitrary version

Keeping that tree at all (or many of) the historical versions on a node is not practical. I wonder what's the use case? if we want to prove some storage slot changed to a certain value at a certain version, a proof for the write set of the txn is sufficient. 

If a proof of the latest value of a slot at a recent version is needed (we keep the trees at the ends of the blocks for the latest 1M versions by default), notice that the SMT exists only at the end of each block, not every specific txn version. -- As you've found out, we do have ways to find the block bounaries for any version.

> but also fetch the corresponding `LedgerInfoWithSignatures` for that specific version so the light client can verify the provenance of the state root Merkle hash used in the `SparseMerkleProof`.

Because we have the "Transaction Accumualtor" -- a complete Merkle Tree consists of TransactionInfo of every historical transaction up until the latest, whose root hash is certified by the LedgerInfoWithSignatures -- everything in the history can be proved against the LATEST root hash -- no need to fetch historical LedgerInfoWithSignatures. 

How it works is roughly like this: the light client fetches and verifies a chain of every END of EPOCH LedgerInfoWithSignatures (Only they matter, because they carriy the ValidatorSet for the new Epoch, knowing which you can validate any LedgerInfoWithSignatures in the next epoch), up until it knows the validator set for the latest / current epoch. a SparseMerkleProof proves a value to the then root hash of the SMT, which is included in the TransactionInfo for the last transaction in a block (as field state_checkpoint_hash). The TransactionInfo is in turn proved to the current root hash included in the latest LedgerInfoWithSignatures via a AccumualtorProof.

If you store the historical Proofs and just need to find out the root hash for those proofs, it's simple: again, the root hash is part of the TransactionInfo, we just need to find the end of block version and fetch the TransactionInfo.

Hope this helps.

**Comment by huitseeker** [comment]
Thanks a ton for those details @msmouse !

Perhaps I can help with a bit of context: the use case is bridging, where each message leads to costs (transaction costs on the recipient chain, among others). 

While proving the result of one specific transaction is definitely a useful bridge message in some latency-sensitive cases, batching is another approach (for cost-minimizing cases) where the latest value at a slot is more useful. In this case, we'd be talking of an `AccountStateProof`, IIUC. Because in this context we're intentionally batching, having a proof of that value only at the block boundary is of course fine.

**Comment by msmouse** [comment]
@huitseeker   That makes much sense. I wonder though, what's your plan for our (many) friend chains that don't have state proofs? 😂

**Comment by huitseeker** [comment]
>  I wonder though, what's your plan for our (many) friend chains that don't have state proofs?

Bridge messages are selected among provable messages. Not trying to change any blockchains here, just trying to craft succint verifiable messages from them. 🤷

> There's no AccountStateProof though, only SparseMerkleProof -- in Aptos the account resource is not a separate first class concept but just another resource in the global state.

Understood: this is just a value at a key. However, I hope my indication helps in figuring out what to serve in #13596.
