### ISSUE TITLE
[Feature Request] Introduce mock framework for unit testing

### ISSUE THREAD

**Issue by sitalkedia** [aptos-labs/aptos-core#219]
# 🚀 Feature Request

Introduce mock framework for easier unit testing.

## Motivation

There is a bunch of manually written Mocks in Aptos code base (refer to `MockSharedMempool` for example). The reason for that being, when the code was written there was no good mock testing framework. https://docs.rs/mockall/latest/mockall/ seems to be a matured framework that is well supported for mock testing. We can introduce this framework and transition these tests to start using the framework.

**Comment by davidiw** [comment]
Interesting proposal! I'd be curious if you could make this into more a first project. For example, the MockSharedMempool is complex code that actually wraps around other dependencies for testing them out, for example the CoreMempool. Is it also testing out other facilities? It isn't super clear to me just from looking at it. I would love to get rid of this hard to read "mock" code. I guess the question is ... if it is a unit test use mocks. if it is an integration test ... ?

**Comment by JoshLind** [comment]
@sitalkedia, yeah, this is something I brought up a while back (1+ years ago):
- The feeling I got at the time was that it's easier/quicker for most folks to roll their own mocks than rely on the libraries that existed back then. I know there's been a bunch of progress made in these libraries since, so perhaps they might better fit the purpose now.
- This definitely seems like something that might help improve the quality/readability of our code, but it's also worth calling out that most of the manual mocks that exist today provide *just enough functionality* to test what the author wanted. So, I think if we did start migrating things, we'd need an end goal that justifies the work. For example, if we're just porting for the sake of it, it's probably not worth it. But, if we can show that we're getting better test coverage, debuggability, etc, then it could be argued this is a good use of time.

**Comment by sitalkedia** [comment]
@davidiw , @JoshLind - Thanks a lot for the feedback. Mock testing in my experience is more suitable for unit tests that are well contained in a class - it is not so well suited for integration testing like scenarios. Also, I don't want us to rewrite a bunch of already written tests just for the sake of bringing in the mock testing framework - that is definitely not the best use of our time. However, I definitely see a great value in using a mock testing framework going forward to make it easier for us to add unit tests. How about we can introduce the framework as a part of existing projects and transitioning any existing tests can be a lower priority for us?
