### ISSUE TITLE
[Bug] aptos move publish

### ISSUE THREAD

**Issue by vietanhvo** [aptos-labs/aptos-core#2751]
# 🐛 Bug
when I run the command
```bash
aptos move publish --package-dir ~/aptos-core/aptos-move/move-examples/hello_blockchain/ --named-addresses HelloBlockchain=default
```
Result:
{
 "Error": "API error: Request failed: RestError { code: 400, message: \"invalid transaction: INSUFFICIENT_BALANCE_FOR_TRANSACTION_FEE\", aptos_ledger_version: None }"
}
However, my wallet had 500000 coins.
Aptos cli version 0.2.3

**Comment by gregnazario** [comment]
Is this against devnet or a local testnet?

**Comment by vietanhvo** [comment]
I am working on devnet

**Comment by RoamWang** [comment]
encountered with the same issue, wait for replay

**Comment by wrwg** [comment]
Could you run `aptos move publish --help` and show us the complete output?

**Comment by wrwg** [comment]
Alright because you have option `--legacy-flow` you are actually not using the CLI from the last devnet release but from some recent head. Can you check whether with option `--legacy-flow` things work?

**Comment by wrwg** [comment]
Better than trying with legacy flow, can you try to use the `--max-gas` parameter to something somehow lower then your account balance? It appears the aptos CLI you are using has a very high default value here which is larger than your account balance (which is the actual bug here). You can see the default on the screnshot,

**Comment by RoamWang** [comment]
sir, it's also failed. but different error.
![1660181102255](https://user-images.githubusercontent.com/12790832/184049565-c448aaad-1221-423c-98e0-3352094bf687.png)

**Comment by wrwg** [comment]
I guess this results from an inconsistency when running a new Aptos CLI against the older devnet. In the most recent code, I can't even find the abort code generated here.

If you want to work from head, you may be better off starting a local testnet via the CLI. Documentation has been added recently. Otherwise the next devnet release is on its way out.

**Comment by RoamWang** [comment]
thank you, sir. I will try to run local testnet.
