### ISSUE TITLE
On-Chain fullnode discovery and tooling

### ISSUE THREAD

**Issue by sherry-x** [aptos-labs/aptos-core#305]
Build tooling to allow fullnode register their address on-chain, for discovery

**Comment by gregnazario** [comment]
This involves needing onchain discovery as well, which is a decently large task.  There's pieces in the codebase in the aptos framework for it, just the discovery needs to be fixed and adjusted

**Comment by davidiw** [comment]
Might be worth  brainstorming here a bit, what type of on-chain registering can we do?
* Each peer can register in their own account
* This can be emitted as an event
* We can have a query to an indexer return a random sampling of these (or even have a tool that does health checks on these)
* A peer can randomly connect to these until they find one that is healthy

Healthy:
* I have an upstream peer
* I have seen a blockchain update in the past 30 seconds

I worry since we don't have a notion of upstream or distance from validators we don't have a strong definition of healthy. We probably should expose a value of distance from validator in the status message.
