### ISSUE TITLE
[Feature Request] Support U256

### ISSUE THREAD

**Issue by liuxiaobleach** [aptos-labs/aptos-core#3277]
# 🚀 Feature Request
## Motivation

U256 is wildly used in evm chain.
If Aptos chain want to have a more actions with evm or lead evm chain user come to aptos, U256 is required.

U256 is already supported in move repo, is it possible to use it?
https://github.com/move-language/move/blob/main/language/evm/stdlib/sources/U256.move

**Comment by liuxiaobleach** [comment]
> Maybe this will help you? https://github.com/pontem-network/u256

Is this safe? Can aptos provide an offical u256?. I am not sure whether a third-party U256 is a good choice?

**Comment by Krishnacore** [comment]
> > Maybe this will help you? https://github.com/pontem-network/u256
> 
> Is this safe? Can aptos provide an offical u256?. I am not sure whether a third-party U256 is a good choice?

Pontem is an official partner of Aptos, the more you can see for yourself how it is implimented and understand how safe it is

**Comment by wrwg** [comment]
The U256 in the Move repo is only for the special version of Move running on the EVM, it does not work for Aptos or other regular Move-based chains.

The Move Maintainers have already decided a while ago to support U256, but the implementation has been lacking. Rest assured it will be coming later this year.

Closing  this bug here because this kind of work is tracked elsewhere. eg here: https://github.com/move-language/move/issues/382
