### ISSUE TITLE
Ways To Improve Aptos Coin Module

### ISSUE THREAD

**Issue by PaulFidika** [aptos-labs/aptos-core#3850]
I read through the Coin Module today, and I had the following thoughts:

Shouldn't the `freeze_coin_store<CoinType>` function have a corresponding `unfreeze_coin_store` function? Or better yet; we could combine them into one function that accepts a bool determining whether or not we want a CoinStore frozen. I'd think that if an authority can freeze your coins, they SHOULD be able to unfreeze them later on as well.

Also for the CoinStore, we could add the 'store' ability, which would allow CoinStores to be stored (wrapped) inside of other resources if we wanted. Someone might find that useful I imagine? Would adding this ability introduce some sort of vulnerability or concern?

Finally, Coin only has a simple transfer ability. On the other hand, ERC-20 tokens on Ethereum have an 'approval' concept built-in, which was terribly designed and ended up causing millions of dollars to be stolen tbh, but the use-case itself was a good one; what if I want to grant someone else the permission to transfer my tokens on my behalf? Modules using Coin can define their own sort of delegation system using `move_from<Coin<CoinType>>`, but it might be nice to have some sort of delegation-transfer standard built right into the Coin module itself, so that all coins can use it. Or do you think that would be too much of an application-specific use-case and introduce too much complexity into a core module?

**Comment by shayansanjideh** [comment]
> Shouldn't the `freeze_coin_store<CoinType>` function have a corresponding `unfreeze_coin_store` function?

Agreed, this seems like a no-brainer

> Also for the CoinStore, we could add the 'store' ability

Currently coins are registered in the account itself, and any time you want to use a particular coin in a struct you can do so by passing in the generic CoinType. I think what you're describing would result in coins being stored in resources not immediately available to a wallet for example, and thus a user would not be able to track their total balance instantaneously, but would rather have to manually dig through every resource they own that storing a CoinType. I could be wrong however.

> what if I want to grant someone else the permission to transfer my tokens on my behalf?

I think this should be possible via a capability, such as a `TransferCoinCapability`, that the owner of the coin could grant to another address.

**Comment by rafales** [comment]
I'm not against having `TransferCoinCapability` but I want to point out that: the reason it exists for ERC-20 is because of EVM architecture and the fact that contract can't withdraw coins on your behalf no matter what. So we need to pre-approve contract so that then contract may withdraw coins. It forces two transactions. It causes developers to request infinite allowance to reduce amount of transactions or simply out of laziness. Then you end up with a lot of dangling allowances which in turn causes loses because of hacks.

This is different for Aptos as a script can do `coin::withdraw()` and then pass it to the right function. In one function. No need for all this ERC-20 spender craziness.

So the need for spending on someone's behalf isn't that great with Aptos in the first place. That said it still may be useful in some cases but should be discouraged unless actually needed. It also needs a robust way for users to revoke allowances.

**Comment by PaulFidika** [comment]
> I'm not against having `TransferCoinCapability` but I want to point out that: the reason it exists for ERC-20 is because of EVM architecture and the fact that contract can't withdraw coins on your behalf no matter what. So we need to pre-approve contract, so contract may withdraw coins. It forces two transactions. It causes developers to request infinite allowances to reduce amount of transactions or simply out of laziness. Then you end up with a lot of dangling allowances which in turn causes loses because of hacks.
> 
> This is different for Aptos as a script can do `coin::withdraw()` and then pass it to the right function. In one transaction. No need for all this ERC-20 spender craziness.
> 
> The need for spending on someone's behalf isn't that great with Aptos in the first place. That said it still may be useful in some cases but should be discouraged unless actually needed. It also needs a robust way for users to revoke allowances.

Right; it might be too big of an epic to add right now. How do you feel about adding 'unfreeze' though? That would be super easy to implement. I can't think of any reason to not have it, unless the purpose of 'freeze' is to make a balance immutable for some reason.

**Comment by rafales** [comment]
Makes sense to me.

**Comment by davidiw** [comment]
add unfreeze, happy to approve a PR :)

prefer specialized functions rather than the boolean concept.

the store ability seems redundant in that coin is already store... if you want events, better to construct contextually meaningful events imo

the idea of approve better maps to the idea of using resource accounts where you can actually have more explicit definitions... approve is a slippery slope since everything must be statically programmed in move.

**Comment by PaulFidika** [comment]
> add unfreeze, happy to approve a PR :)
> 
> prefer specialized functions rather than the boolean concept.
> 
> the store ability seems redundant in that coin is already store... if you want events, better to construct contextually meaningful events imo
> 
> the idea of approve better maps to the idea of using resource accounts where you can actually have more explicit definitions... approve is a slippery slope since everything must be statically programmed in move.

Okay so you're saying instead of having approvals built into Coin in some fundamental way, we should instead have users store their Coins inside of a resource account, and then we can customize that resource account with various approval functions? I'll look into doing that.

What does statically-programmed have to do with approve being a "slippery slope"? Could you elaborate on that more for me?

**Comment by davidiw** [comment]
statically programmed / lack of dynamic dispatch implies that all functionality must be built within the module itself. If we add an approvals function it would mean the approval have to be defined apriori. We could potentially add new ones, but only if they make sense with the given interface. That's why we emphasize resource accounts / modules so much more, since it places the opportunity to add this into something that isn't fixed. The way I think about it, in Move I can always define a new module to pull data from something and do whatever I want. However, the way in which I push data is always going to be fixed and limited to whatever I define when I build that module.
