### ISSUE TITLE
[Bug] cargo install of CLI fails for version 0.3.3

### ISSUE THREAD

**Issue by gregnazario** [aptos-labs/aptos-core#4024]
# 🐛 Bug

Cargo install from the devnet branch for the cli fails 

## To reproduce

**Code snippet to reproduce**
```rust
cargo install ... --branch devnet aptos 
```

Please comment the following below:
1. Operating system (OS)
2. CPU Architecture (x86, Arm, etc)
3. Command used 
4. Error resulting

Meanwhile have you tried using the prepacked release? https://github.com/aptos-labs/aptos-core/releases/tag/aptos-cli-v0.3.3

**Comment by gregnazario** [comment]
This is due to an unstable feature of tokio https://docs.rs/tokio/latest/tokio/runtime/struct.Builder.html#method.disable_lifo_slot

**Comment by gregnazario** [comment]
I'm removing the cargo install instructions since they seem to be unstable.  Cargo install was installing from source anyways

This PR will ensure there's support on the rest of the systems for from source https://github.com/aptos-labs/aptos-core/pull/4031

**Comment by PaulFidika** [comment]
I was having this issue all day, but I'm using the pre-compiled library now and it's working fine.

**Comment by VishnuKMi** [comment]
1. Ubuntu 22.04 LTS
2. x86_64
3. cargo install --git https://github.com/aptos-labs/aptos-core.git --branch devnet aptos 
4.    = note: collect2: fatal error: id terminated with signal 9 [Killed]
 	   compilation terminated.
 	 
 error: could not compile 'cached-packages' due to previous error
 warning: build failed, waiting for other jobs to finish...
 error: failed to compile 'aptos v0.3.3 (https://github.com/aptos-labs/aptos-core.git?branch=devnet#8f634bcd)', intermediate artifacts can be found at '/tmp/cargo-installOzvrCl'

**Comment by Kabie** [comment]
`RUSTFLAGS="--cfg tokio_unstable" cargo install` works for me.

**Comment by gregnazario** [comment]
What I decided is we've removed the cargo install information.

Most platforms are prebuilt, and anyone who doesn't have it should build by source, because there is a script that handles the dependencies.

This script doesn't cover some platforms at this point (e.g. windows), but we have a build for that.

If there are any platforms that from source instructions don't work, or the prebuilt binaries, please note it here.
