### ISSUE TITLE
[Feature Request] Make `aptos_stdlib::simple_map` iterable

### ISSUE THREAD

**Issue by fardream** [aptos-labs/aptos-core#4110]
# 🚀 Feature Request

Add an iterator interface to `aptos_stdlib::simple_map::SimpleMap` (like [`IterableTable`](https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/move-examples/data_structures/sources/iterable_table.move).

## Motivation

We intend to use `simple_map::SimpleMap` as a lightweight replacement for `IterableTable`.

## Pitch

Given that `simple_map` already provides a length accessor, we can simply add accessors by index

```move
    public fun borrow_at_index<Key: store, Value: store>(
        map: &SimpleMap<Key, Value>,
        idx: u64,
    ): &Element<Key, Value> {
        vector::borrow(&map.data, idx)
    }

    public fun borrow_at_index_mut<Key: store, Value: store>(
        map: &mut SimpleMap<Key, Value>,
        idx: u64,
    ): &mut Element<Key, Value> {
        vector::borrow_mut(&mut map.data, idx)
    }
```

To support operations on `Element`, we also need to add the following accessors

```move
    public fun element_key<Key: store, Value: store>(elem: &Element<Key, Value>): &Key {
        &elem.key
    }

    public fun element_value<Key: store, Value: store>(elem: &Element<Key, Value>): &Value {
        &elem.value
    }

    public fun element_value_mut<Key: store, Value: store>(elem: &mut Element<Key, Value>): &mut Value {
        &mut elem.value
    }
```

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

Yes.

**Comment by PaulFidika** [comment]
I've been making maps iterable by maintaining a separate vector which acts as an index. But it would be a lot simpler to have it all in one package. I assumed maps are not iterable on purpose to make them more space efficient?

**Comment by wrwg** [comment]
We don't want those Maps be iterable because there is no way how a tool like the Move Prover can reason about ordering -- and henceforth the semantics of iteration - as long as ordering is defined as converting the value to BCS and then comparing the byte vectors... Unless either Move has a well-defined `<` operator, or maps are using insertion order, this doesn't woprk. As @PaulFidika says you can build your iterable map on top. I suggest that should have insertion order. The fact that SmallMap uses ordering internally is implementation detail.
