### ISSUE TITLE
[Bug] Multiple rapid faucet requests re-use sequence numbers

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#4431]
Note, the title is just a theory explaining the issue. From the wallet we're seeing this:
```
➜  wallet git:(webrequest) ✗ curl 'https://faucet.testnet.aptoslabs.com/mint?address=6339e0cd3a3731a2e0cbf5d0448ee506b0be65b9862722a693ede70822a421b1&amount=100000000' \
  -X 'POST' \
  -H 'authority: faucet.testnet.aptoslabs.com' \
  -H 'accept: application/json' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'content-length: 0' \
  -H 'cookie: _ga=GA1.1.1946646854.1663570066; _ga_CWW2TW4HSD=GS1.1.1663570065.1.1.1663570119.0.0.0; _ga_8XH7V50XK7=GS1.1.1663789881.1.0.1663789881.0.0.0' \
  -H 'origin: chrome-extension://ejjladinnckdgjemekebdpeokbikhfci/' \
  -H 'sec-ch-ua: "Google Chrome";v="105", "Not)A;Brand";v="8", "Chromium";v="105"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36' \
  --compressed
API error Error(InvalidTransactionUpdate): Transaction already in mempool with a different payload%
```

This implies that the way we're managing the LocalAccount in the faucet isn't correct since we're re-using sequence numbers for different requests with different payloads.

Given we're using the same account from multiple faucet instances, it's likely that. We do have code that attempts to deal with sequence number clashes, but it's clearly not doing its job if we're seeing the above error.

**Comment by banool** [comment]
cc @hariria

**Comment by banool** [comment]
One solution would be to stop sharing an account between multiple instances and instead use one account per instance, like we do in the tap. This could probably work with the minting solution too, since we're delegating mint capabilities to a new account anyway.

**Comment by hariria** [comment]
Sounds good to me :)

**Comment by davidiw** [comment]
> One solution would be to stop sharing an account between multiple instances and instead use one account per instance, like we do in the tap. This could probably work with the minting solution too, since we're delegating mint capabilities to a new account anyway.

This is already the default behavior. The issue here is a matter of the faucet just getting hammered so hard and then resetting. The correct behavior is for it to track when a txn was submitted and when it is safe to assume it was unsuccessful and reset its sequence numbers. We have a 30 second transaction expiration time and a 30 second reset. My guess is that there's a slight clock skew where a garbage collection in mempool has yet to taken place. This is very unfortunate and I'm not sure there's much we can really do. We could hold on to the request at faucet and keep trying. We could let the user know we're overloaded. But this is not a bug, not a feature.

Please fix upstream in the client. Note, we have plenty of faucets, so trying again will likely remedy the issue.
