### ISSUE TITLE
[Feature Request] Add Base64 Support 

### ISSUE THREAD

**Issue by 99Kies** [aptos-labs/aptos-core#4599]
# 🚀 Feature Request

Add Base64 Support On Move

## Motivation

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

## Additional context

<https://github.com/99kies/aptos-core>

**Comment by 99Kies** [comment]
@vgao1996  Now there is a question that needs to be discussed, whether to put the base64 support in the native or to make a pure move dependency.

**Comment by jerome-chen** [comment]
+1. implementing purely in move is possible but far less efficient.

**Comment by vgao1996** [comment]
Yeah I would say that if we do end up adding the base64 functions then they should be implemented as native functions or otherwise they would be prohibitively expensive

**Comment by 99Kies** [comment]
@vgao1996 If we decide to go with adding native functions, then I'll resubmit pr. One last question, if we add new native functions, does aptos need to do a fork to support?

**Comment by wrwg** [comment]
We'll add the native functions to the Move language repo, in the stdlib, I think. There is a process for adding natives which is rather complex, and we would do this with a bunch of other natives for strings. We probably prefer to do this inside of the team because of all the context required, so no need to resubmit, but thank you for the initiative.
