### ISSUE TITLE
[Feature Request] Allow transaction simulation for transaction with higher nonce

### ISSUE THREAD

**Issue by JackyWYX** [aptos-labs/aptos-core#5066]
# 🚀 Feature Request

Currently, simulating a transaction with high nonce will return a vm_status:

```
vm_status: 'Transaction Executed and Committed with Error SEQUENCE_NUMBER_TOO_NEW',
```

We would request to allow simulation result to be displayed for higher sequence number.

## Motivation

There is some uses cases that will need to simulate a transaction with a higher nonce, For example, for multi-sig wallet. It is expected that there are multiple pending transactions in the transaction queue. Without simulation for transaction for higher nonce, the max gas is not able to be obtained for future transactions. 

## Pitch

Allow simulation for transaction nonce is higher. Increase the sequence number with test only native function in MOVE virtual machine.

**Comment by davidiw** [comment]
This gets tricky... because what you want is fine grained simulation support. Specifically in this case, we have a move prologue that validates gas and sequence number and an  epilogue that bumps sequence number and gas. We cannot skip these without devaluing the process. It is also not particularly cost effective for transactions to split these for fine grained simulation.

Might I ask why you want this feature outside of ... the error sucks?

**Comment by JackyWYX** [comment]
What we want is just gas used in simulation. Is there a work around?

**Comment by davidiw** [comment]
Let me merge this into another issue on improving simulation.
https://github.com/aptos-labs/aptos-core/issues/5928
