### ISSUE TITLE
[Bug] website link broken

### ISSUE THREAD

**Issue by Flofie** [aptos-labs/aptos-core#5327]
Website Link is broken since yesterday. 

https://aptos.dev/nodes/indexer-fullnode/full-node/fullnode-source-code-or-docker/#method-1-building-and-running-from-source

**Comment by clay-aptos** [comment]
@Flofie I think you are looking for this:
https://aptos.dev/nodes/full-node/fullnode-source-code-or-docker/#method-1-building-and-running-from-source

Because there have been no changes to the indexer page recently (yet):
https://github.com/aptos-labs/aptos-core/commits/main/developer-docs-site/docs/nodes/indexer-fullnode.md

May I ask where you got the link above? Does that exist somewhere on our site? Please reopen when you have those details. Thanks!
