### ISSUE TITLE
Test Error

### ISSUE THREAD

**Issue by Grumpy-Gorilla** [aptos-labs/aptos-core#5373]
### Please note that this issue tracker is not a help form and this issue will be closed.

Please contact the development team on [Discord](https://discord.gg/aptoslabs)

I wanna deploy minting contract to my account.
and I tried it.
the code is http://github.com/aptos-core/aptos-move/move-examples/mint_nft/sources/minting.move.
but in the test mode, error emitted.
error is 

![image](https://user-images.githubusercontent.com/66923479/199097817-2d75a756-6e87-40ce-b344-2b94de8bc3b9.png)

how to solve it?

**Comment by chloeqjz** [comment]
Could you provide us what were your steps to deploy the contract? It's likely that you're calling the `retrieve_resource_account_cap` with a resource signer that is not created by the source address. Also could you try rebasing off main? We added an explicit error code for this `EUNAUTHORIZED_NOT_OWNER`. 

If you're publishing the `minting.move` contract, you need to create a resource account from a source account, and publish the contract under the resource account's address. Otherwise it'll have this error because it is unable to find the specified resource account under the source account's `Container` which is a `SimpleMap` that stores <resource account address, resource account's signer capability>.
