### ISSUE TITLE
[Bug] is `module_bundle_payload` still supported?

### ISSUE THREAD

**Issue by xiadd** [aptos-labs/aptos-core#5384]
# 🐛 Bug

I read doc in https://aptos.dev/guides/interacting-with-the-aptos-blockchain/#publishing-a-new-move-module, and it says that `module_bundle_payload ` is still working, But in [this issue](https://github.com/aptos-labs/aptos-core/issues/3581#issuecomment-1230838332) @jjleng said that `module_bundle_payload` is not supported anymore.

## Additional context

And I wonder is it possible to publish a module with petra wallet? I've tried a lot but failed

**Comment by movekevin** [comment]
No it has been deprecated in favor of the new flow via the code module: https://aptos.dev/tutorials/first-move-module

**Comment by movekevin** [comment]
No I don't think it'd be supported in Petra due to needs to compile Move source code.

**Comment by movekevin** [comment]
I think uploading module is rather low in priority for wallets. Why not use the Aptos CLI?

**Comment by wrwg** [comment]
The concept of 'publishing a module' is not supported for Aptos Move, only publishing a package. This package must be build by the standard build process using `aptos move compile`. You cannot use a standalone version of the Move compiler, because there is additional metadata and post processing required for Aptos Move. That being said, if you use the `aptos move compile` in your docker, you should be able to extract bytecode and metadata and construct a code publish transaction for the `code` module. Closing for now, reopen for more questions.
