### ISSUE TITLE
[RFE] Create Validator Fullnode (VFN) docs

### ISSUE THREAD

**Issue by clay-aptos** [aptos-labs/aptos-core#5518]
# 🐛 RFE

Validator Fullnodes (VFNs) are another area of confusion with our users and in our docs. We don't define them in the glossary, and mention them in passing in the docs. No dedicated instructions exist. Let's fix that.

@wintertoro indicates @sherry-x is the source of truth. No surprise there. Sherry, let's talk when you come up for air. Thanks!

**Comment by clay-aptos** [comment]
@sherry-x do you think a glossary entry would suffice?

**Comment by JoshLind** [comment]
@clay-aptos, a glossary entry would probably suffice, i.e., a VFN is:

A fullnode that can connect directly to a validator. Public fullnodes (PFNs) cannot connect to validators because of security concerns. Thus, validator operators typically run at least one VFN so that PFNs connect to these VFNs.

To define a PFN, it is simple a fullnode that is run by someone who is not a validator operator. The only difference between a VFN and a PFN is whether or not the node can connect directly to a validator 😄 

Does that make sense?

**Comment by clay-aptos** [comment]
> @clay-aptos, a glossary entry would probably suffice, i.e., a VFN is:
> 
> A fullnode that can connect directly to a validator. Public fullnodes (PFNs) cannot connect to validators because of security concerns. Thus, validator operators typically run at least one VFN so that PFNs connect to these VFNs.
> 
> To define a PFN, it is simple a fullnode that is run by someone who is not a validator operator. The only difference between a VFN and a PFN is whether or not the node can connect directly to a validator 😄
> 
> Does that make sense?

Thanks, Josh! Sure does. I went with a list in Node Networks and Sync instead:
https://github.com/aptos-labs/aptos-core/pull/6097

Let me know what you think. Thanks!
