### ISSUE TITLE
[Bug] Make the query "resource account" go to the resource account page at first

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#5662]
Or more broadly, make the search feature show the most relevant result first. Whether that means tweaking the engine, replacing it, or tagging the content of the docs site somehow, remains to be seen.

**Comment by clay-aptos** [comment]
Tagging onto this, it would be good to have a standalone page for all search results rather than the floating box you cannot link to or peruse other entries. Right now, we must search each time to find another result to try.

That said, I'd rather have the Authors list at the bottom of all pages. :-D
@moonclavedev, should I file a separate issue for the standalone search results?

I know you said you didn't need an issue for the Authors list, but I am not sure how else to track it. Thanks!

**Comment by clay-aptos** [comment]
This now works for me. @banool care to try again?

**Comment by clay-aptos** [comment]
This works as intended.
