### ISSUE TITLE
[Mempool] Reduce N^2 communication in validator network

### ISSUE THREAD

**Issue by davidiw** [aptos-labs/aptos-core#581]
Currently each mempool node broadcasts each of its transactions to every other node in the network. This can result in N^2 communication costs and add substantial overhead to making progress in Consensus. We can at least make it N communication cost by not adding the transactions to the same timeline that is used to broadcast out the transactions to other nodes at the validator layer.

**Comment by zekun000** [comment]
We're going to leverage proof of availability to optimize the mempool, not getting rid of N^2 communication but to better batch/improve throughput

**Comment by gregnazario** [comment]
So you're saying we'll still broadcast to everyone always?

**Comment by zekun000** [comment]
we'll broadcast and get ack from 2/3 stakes and move on. need subcommittee too if the N grows big

**Comment by bchocho** [comment]
Closing.

(1) This turned out not be true:

is_upstream_peer returns true for a validator, so we’re not re-broadcasting stuff from other validators (set to `TimelineState::NonQualified`)
https://github.com/aptos-labs/aptos-core/blob/b9faf4b2eb6d8fae094123306cdc28c05be92a6b/mempool/src/shared_mempool/network.rs#L250

(2) We are also working on Quorum Store based optimizations
