### ISSUE TITLE
[Feature Request] Cleanup SDK generator for ABIs

### ISSUE THREAD

**Issue by gregnazario** [aptos-labs/aptos-core#5986]
# 🚀 Feature Request

Some people want to generate ABIs for their code, and there's a mostly working generator existing already.

## Motivation

**Is your feature request related to a problem? Please describe.**
The [aptos-sdk-builder](https://github.com/aptos-labs/aptos-core/tree/main/aptos-move/aptos-sdk-builder) is a pretty good tool for Rust bindings, and is used throughout the aptos-core codebase.  But, it has some downfalls & is missing some documentation on how to use it fully.

## Pitch

**Describe the solution you'd like**
Get the aptos-sdk-builder in a place where people can use it to generate ABI bindings in Rust first, then possibly Go and other languages.

## Additional context

Let's list any rough points here that need to be cleaned up 

- [ ] Documentation on how to run
- [ ]

**Comment by bonedaddy** [comment]
For rust the issue seems to be related to two methods of code generation, one with "local types" the other without.

The comments for `aptos_sdk_builder::rust::output` seem to indicate that `local_types` when set to true is intended to be used within the aptos codebase itself,  however I don't believe this is the case. When `local_types` is set to false, the way structs etc.. are generated are using the private initializers, only available within the crate the type is defined in.
