### ISSUE TITLE
[Feature Request] Allow Source account to Acquire its resource account's signer

### ISSUE THREAD

**Issue by areshand** [aptos-labs/aptos-core#5988]
# 🚀 Feature Request

## Motivation

Bob has an admin account owning multiple resource accounts. Bob uses a 3rd party contract to manage these accounts to do common functionality like:
* transfer APT from a resource account to other accounts
* update NFT collection maximum of an NFT collection created by a resource account
* transfer APT from one account and do operations on another NFT resource account
* ... ...

Bob likes the UI of the 3rd party contract and easy integration. But Bob is very keen on the ownership and doesn't want 3rd party platform to have too much power over his resource accounts. Bob wants to authorize the txn himself. Bob doesn't want the platform has the power to do the operations without his approval.

**Comment by davidiw** [comment]
This makes sense and all, but I think there's a bigger play here around how to effectively sandbox accounts. This is a cross-layer problem. I think this is also somewhat a duplicate issue of ... https://github.com/aptos-labs/aptos-core/issues/5055

Why is this cross layer? Because without any adjustments, you'll need to invoke scripts and assume the entry functions are public. It also requires the ability to seamlessly identify available resource accounts, select which one, and then import the entry function, place it into a script, and compile it.

feel free to push more content there or let's actually start building out a sandbox account strategy...

**Comment by areshand** [comment]
After reading #5055, I think the issue is more related to the signer being abused to transfer all funds of an account if I understand the problem correctly.

Here, the issue is more on the abuse of signer capability, which is saved by platform contracts and can gain the signer even when the user doesn't approve. 
If we don't allow source account owner to obtain the signer of their own resource accounts, we will see these signer capability being stored everywhere, which is a terrible situation.
