### ISSUE TITLE
[Docs] make verify node connections easier to find

### ISSUE THREAD

**Issue by michelle-aptos** [aptos-labs/aptos-core#6015]
# Aptos Documentation Issue

## Location

https://aptos.dev/nodes/validator-node/operator/connect-to-aptos-network#verify-node-connections

This information is currently under Run Nodes: Install Validators -> Connecting to Aptos Network 

It would be clearer to break out the "Verify Node Connections" section into it's own page so that it appears in the column side bar

It might also be more intuitive to link to this section from these pages:

https://aptos.dev/nodes/node-health-checker/index
https://aptos.dev/nodes/validator-node/operator/node-liveness-criteria

## Description

It's a bit hard to find this information right now since it's buried deep in the "Connecting to Aptos Network" page

The structure of the page

Link to other pages, create a new page

## Audience

Validator operators

Check if their VFN is connected to the validator

**Comment by clay-aptos** [comment]
Thanks for the issue, @michelle-aptos ! Stand by for updates.

**Comment by clay-aptos** [comment]
Shifting around yet still on my calendar to get to this soon.

**Comment by clay-aptos** [comment]
Hi @michelle-aptos and team, I have started these changes in:
https://github.com/aptos-labs/aptos-core/pull/7543

As you can see, I am editing the contents and linking out to relevant materials where needed. Here are some questions to make things even more clear:

1. In the **Staking** concept, we hint at minimum and maximum requirement yet don't spell them out. So I have copied the minimum from the **Connect to Aptos Network** instructions to the concept. What is the maximum?

2. Why do these seeming duplicate instructions exist?
https://aptos.dev/nodes/local-testnet/using-cli-to-run-a-local-testnet
https://aptos.dev/cli-tools/aptos-cli-tool/use-aptos-cli/#running-a-local-testnet

3. In **Connect to Aptos Network**, when we say "Update `chain_id` to 1 (for mainnet)" is that still correct given the chain ID updates we have released?

This is a non-blocker but one for those node improvements I want to help with:
We have a lot of repetition in different connection paths (ex. Docker, Terraform, etc.) I imagine that is intentional yet would still like the team's permission to consolidate. Please let me know. Thanks!

**Comment by rktoshavat** [comment]
I thing something are change and it's became better.
