### ISSUE TITLE
[Contracts] Improve NFT Token standard

### ISSUE THREAD

**Issue by davidiw** [aptos-labs/aptos-core#611]
- [x] Add events for token claim and remove ownership
- [x] Add events for collection and token creation
- [x] Derive NFT Token as a wrapper around the upcoming Simple Token
- [ ] Create a marketplace contract that parallels TokenTransfer.move
  * Specify a price for a given token and optionally an individual that can claim it
  * Upon transferring the coin to the contract, the contract gives it to the original owner, the token is claimed by the user
- [ ] Create an auction that parallels TokenTransfer.move
  * Specify a base price, minimum selling price, and a timestamp for the auction
  * Individuals can bid, maximum bid is kept, every successful bid results in an event
  * Bids must be locked into the system
    * Highest bid causes the paid bid to be returned to that individual
    * Last highest bid after timestamp expired can be claimed by the original NFT owner or will be sent when NFT is claimed
  * After timestamp > system timestamp, no more bids
  * Highest bidder can claim token
- [x] Evaluate costs associated with changing the data model:
  * Token { id, balance }
  * New Table on creator <ID, TokenData>, extend TokenData to contain collection name
  * Replace Collections (Table<String, Table<String, TokenData>>) with (Table<String, Table<String, ID>)
- [ ] Replace the Token tutorial with a Token standard doc
- [x] Work with the storage team to create an Token ownership indexer and remove claimed_tokens from the contract
- [ ] Explore the concept of allowing users to unilaterally send Tokens
  * Biggest issue now is that a user must first have a Gallery for the specific token type
  * If that exists, maybe we can explore either flags, capabilities, acls or other means to allow air drops, etc

**Comment by davidiw** [comment]
@msmouse , curious your opinion around: "Evaluate costs associated with changing the data model:"

**Comment by msmouse** [comment]
@davidiw  Looks like what you suggest is beaking the `TokenData` out to a table where you can look up by `ID` directly. While that's reasonable and ergonomic, do you find it acceptable to make a 
```
struct TokenId {
    creater_address: address
    collection_name: String,
    token_name: String,
}
```
So that we make the read more expensive, but make one less global item per token created? (At the same time the Id itself is more informative)

------

And what worries me more is "Work with the storage team to create an Token ownership indexer". Please let's agree that it is at least not part of the core DB.

**Comment by sitalkedia** [comment]
@msmouse, @davidiw  - Does it makes sense for us to implement FatTable implementation to reduce the number of global items we create for this?

**Comment by msmouse** [comment]
I can imagine a FatTable with vectors or local mapping serialized as blobs as buckets as an optimization for a general purpose table. But it's more strightforward for tables with relatively predicable size (so that a re-hash is not really necessary ever). In this case, I think we should stay with the normal table for now.

**Comment by davidiw** [comment]
@msmouse 

> And what worries me more is "Work with the storage team to create an Token ownership indexer". Please let's agree that it is at least not part of the core DB.

Not part of core DB :)

> ```
> struct TokenId {
>    creater_address: address
>    collection_name: String,
>    token_name: String,
>}
>```

Hmm... This is an interesting proposal. In this case, we never explicitly store a TokenId in storage -- it is used purely as a resource access path? I think this is ... a little unconventional but I like it. I'll update the issue with this proposal in a bit.

**Comment by davidiw** [comment]
Closing out as most of this has been done and we should break out the remainder.
