### ISSUE TITLE
[Docs] Define release process and build list of all releases by product

### ISSUE THREAD

**Issue by davidiw** [aptos-labs/aptos-core#6373]
# Aptos Documentation Issue

Make it easier to find the latest released software version per network, so that when we're asked for the latest release, we have a definitive source that we can then share with partners without having to do anything more than copy paste a link.

It'd be great to have this across the various networks and node, indexer, cli (others?)

## Location

Probably somewhere on the docs page
and ideally automated

**Comment by clay-aptos** [comment]
Thanks, @davidiw . We could publish a table resembling: Service |  Versions (latest on top)  | Supported Networks (*net) |  Release Notes

Should we also attempt to employ the standard GitHub flow for releases?
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes

As @perryjrandall suggested:
the benefit to a release yml are two fold:
* It allows you to couple the changes to the commit itself
* It allows us to use github to automagically generate the release notes

Regardless, we need to nail down the collection of changes. I suggest iteratively rather than at the end of a release as I am certain things might be missed. Further, it would help ensure we poll for associated doc updates.

**Comment by clay-aptos** [comment]
I am noting we are getting guidance from our wonderful product management team in an internal page titled *Review Release Notes Workflow*. Thank you, @thepomeranian and @michelle-aptos !

**Comment by clay-aptos** [comment]
@christian-aptos wants to help. Let's do this!

**Comment by clay-aptos** [comment]
@sherry-x , do you think we could and should link from release notes line items to the respective commits? In lieu of that, should we link to queries such as this for all deltas?
https://github.com/aptos-labs/aptos-core/compare/aptos-node-v1.1.0...aptos-node-v1.2.4

**Comment by clay-aptos** [comment]
Hi team, per @thepomeranian I have started to experiment with linking to specific releases from the Start menu on Aptos.dev:
https://github.com/aptos-labs/aptos-core/pull/6657

I still think we might want a table to depict all of the releases per network.

**Comment by clay-aptos** [comment]
Let's try that table as the index page for these contents. The inline releases link may not scale well or perhaps could live lower in the Start menu. We still need to add to top nav too.

**Comment by clay-aptos** [comment]
@thepomeranian , perhaps we can leverage simple steps like having eng keep changelogs we may harvest prior to release:
https://keepachangelog.com/en/1.0.0/

**Comment by clay-aptos** [comment]
I am introducing a *release-notes* tag in the following PR to see if we can better identify all of the changes that should be highlighted in the associated release notes:
https://github.com/aptos-labs/aptos-core/pull/6823

Allowing a simple query for all:
https://github.com/aptos-labs/aptos-core/labels/release-notes

@thepomeranian, @sherry-x and team, please let me know what you think.
