### ISSUE TITLE
[Bug] CLI pointing to the wrong network

### ISSUE THREAD

**Issue by lbmeiyi** [aptos-labs/aptos-core#6528]
What: CLI shows mainnet, but directs to testnet.

**Comment by e99243506bigplay** [comment]
Check your `.aptos/config.yml`, make sure your rest_url is right. and check which profile using on your command line.

**Comment by michelle-aptos** [comment]
rest-url defaults to devnet even when the correct url is provided. example on this page: https://aptos.dev/nodes/validator-node/operator/staking-pool-operations/ if you run the below command

```
aptos init --profile mainnet-operator \
--private-key <operator_account_private_key> \
--rest-url https://fullnode.mainnet.aptoslabs.com/v1 \
--skip-faucet
```

you will get this error:

`zsh: no such file or directory`

the alternative right now is to run ```aptos init --profile mainnet-operator \``` then select mainnet 

this means that either all of the docs with --rest-url need to be updated or we fix this so that the rest-url directs to the right network

**Comment by gregnazario** [comment]
Yeah, all the docs should be updated to use network instead of rest URL
