### ISSUE TITLE
[Feature Request] Iterator in AptosFramework::Table

### ISSUE THREAD

**Issue by MartianSiddharth** [aptos-labs/aptos-core#660]
# 🚀 Feature Request

Requesting an iterator or some way to iterate over the Table.

## Motivation

**Is your feature request related to a problem? Please describe.**

I am writing Move modules where I need to maintain a max value in the table. If the max value is removed, I will need to iterate the Table to retrieve the next max value.

## Pitch

**Describe the solution you'd like**

A function that enables iterating over the keys, and values of Table. 

**Describe alternatives you've considered**

An alternative approach would be to make a custom data structure using Vectors, but it would be inefficient. I am aware that the current Tables implementation uses Vectors and the code might be replaced with something efficient. 

My request is that exposing an interface now will be a good idea so that when the implementation of Table is changed in the future, those interfaces will remain the same and all the modules depending on them will not be affected.
**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes

**Comment by msmouse** [comment]
Just throwing out thoughts off the top of my head:

A iteratable mapping structure can be defined using two basic tables, one holding not only the KV, but also an u64 index in another table; the other uses u64 as the key, keeping the order of insertion.  The first item inserted will have index 0, the second has 1, etc. Some tricks need to be played around removals though -- maybe swap the last inserted item to the new empty spot in the index table.

If the total number of items are small, you can use the vector in place of the index table.

```
struct Map<K, V> {
    values: Table<K, (u64, V)>;
    index: Table<u64, K>; 
}
```

The reason the stdlib can't provide an iteratable table is the authentication data structure (Sparse Merkle Tree and friends) can't prove (to a remote reader in a trustless way) that two logically adjacent items are indeed next to each other without other items in between, and that's in turn because of the fact that we authenticate the items NOT in the logical order according to their developer facing keys.
