### ISSUE TITLE
what is NODE_URL and FAUCET_URL in MainNet aptos

### ISSUE THREAD

**Issue by gitsupi** [aptos-labs/aptos-core#6693]

**Comment by clay-aptos** [comment]
What doc?

**Comment by clay-aptos** [comment]
From:
https://aptos.dev/tutorials/your-first-transaction/

```
export const NODE_URL = process.env.APTOS_NODE_URL || "https://fullnode.devnet.aptoslabs.com";
export const FAUCET_URL = process.env.APTOS_FAUCET_URL || "https://faucet.devnet.aptoslabs.com";
```

Does that answer your question?

**Comment by clay-aptos** [comment]
I am asking @christian-aptos to take a look at this.

**Comment by saharct** [comment]
Hi @gitsupi , did Clay answer your question?

If you were asking for their purpose:
- NODE_URL and FAUCET_URL are both environment variables set to their respective Aptos service URLs.

If you were asking for their mainnet equivalents:
- NODE_URL for mainnet is https://fullnode.mainnet.aptoslabs.com/v1
- FAUCET_URL for mainnet doesn't exist because there is no faucet on mainnet.
- You can find other Aptos service URLs for mainnet in [Getting Started](https://aptos.dev/guides/getting-started/#aptos-mainnet).

**Comment by gregnazario** [comment]
There is a great page for all of this information here:
https://aptos.dev/guides/system-integrators-guide/#production-network-access
