### ISSUE TITLE
[Docs] Mention `legacy_entry_fun`

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#6863]
# Aptos Documentation Issue

## Location

None, which is the problem :P

## Description

There should be a mention of `legacy_entry_fun` in the docs. Ideally it lives beside the error message that you get if you don't use it.

Some context:
> How do I upgrade a module that contains an entry function with a return value? If I remove the function, I will get ‘BACKWARD_INCOMPATIBLE_MODULE_UPDATE’ when upgrading. If I don’t modify it, I will not able to compile it and get ‘error: entry function cannot return values’. Is there any solution?

More context: https://aptos-org.slack.com/archives/C036X27DZNG/p1677773289875239.

Example usage: https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/aptos-framework/sources/coin.move#L364.

## Audience

Move devs who have older modules deployed on chain.

**Comment by saharct** [comment]
@banool @movekevin I was going to create a Move Compiler section in the [Handling Errors](https://deploy-preview-7208--aptos-developer-docs.netlify.app/guides/handle-aptos-errors/) doc, but after discussing this with @wrwg, I think we should avoid documenting compiler error messages since they will de-sync frequently. Also, the #[legacy_entry_fun] attribute received its own section in [Aptos Node Release v1.2.4](https://github.com/aptos-labs/aptos-core/releases/aptos-node-v1.2.4), so we can link that to anyone who needs more information about it. 

Since this only applies to older code written in a certain way, devs will find out when they update and receive the compile-time error. I don't think we should mention it in the docs without the associated error message, as this workaround won't be discovered anyways. @clay-aptos what do you think? See the [full discussion on Slack](https://aptos-org.slack.com/archives/C036X27DZNG/p1679075937081269) for more details.

**Comment by clay-aptos** [comment]
Thanks, @saharct . Perhaps we can add this information here:
https://aptos.dev/issues-and-workarounds

That is the closest we have to a troubleshooting FAQ now. No Move content there, only Nodes. We can always split that and place in their respective sections of the site. Let's start there though.

**Comment by saharct** [comment]
Hi @clay-aptos, the relevant changes can be found in [PR 7549](https://github.com/aptos-labs/aptos-core/pull/7549).
