### ISSUE TITLE
[Feature Request] Add chunkwise publication for large packages

### ISSUE THREAD

**Issue by alnoki** [aptos-labs/aptos-core#6905]
Currently, the Aptos transaction size limit prohibits the publication of larger packages.

This proposal includes sample code snippets (not compiled or tested, just reference algorithms) that could be included in `aptos_framework::code` to eradicate this issue.

Basically, the `StagingArea` holds publication data that is submitted to the chain across several chunked transactions, stored in a format later used for `aptos_framework::code::publish_package_txn()`.

With `stage_code()`, a publisher can chunk out publication data bytes across multiple transactions that each fit within Aptos transaction size constraints, then call `publish_staged_code()` to publish everything in the staging area.

Note that this proposal does not include error checking, the ability to clear out the staging area after a faulty chunking operation, or other fault mitigants. Rather, this proposal simply presents the requisite algorithmic design necessary for the core functionality.

@davidiw @movekevin @chen-robert

---

```move
module aptos_framework::code {

    struct StagingArea has key {
        metadata_serialized: vector<u8>
        code: vector<vector<u8>>,
    }

    public entry fun stage_code(
        owner: &signer,
        bytes: vector<u8>,
        is_package_metadata: bool
        new_module: bool // Ignore if is package metadata.
    ) acquires StagingArea {
        // Get publisher address.
        let publisher_address = address_of(publisher)
        // Create staging area under publisher account if needed.
        if (!exists<StagingArea>(publisher_address)) {
            metadata_serialized = vector::empty();
            code = vector::empty();
            move_to(owner, StagingArea{metadata_serialized, code});
        }
        // Mutably borrow staging area.
        let staging_area_ref_mut =
            borrow_global_mut<StagingArea>(publisher_address);
        // Declare mutable reference to bytes vector to append to:
        let to_append_to_ref_mut = if (is_package_metadata)
            // If package metadata, is package metadata vector.
            &mut staging_area_ref_mut.package_metadata else { // If not:
            // Mutably borrow code vector.
            let code_ref_mut = &mut staging_area_ref_mut.code;
            // Get module count.
            n_modules = vector::length(code_ref_mut);
            if (new_module) { // If new module:
                // Push back empty vector for module's code.
                vector::push_back(code_ref_mut, vector::empty());
                // Increment module count.
                n_modules = n_modules + 1;
            };
            // "Return" from conditional block a mutable reference to
            // final bytes vector in code vector.
            vector::borrow_mut(code_ref_mut, n_modules - 1)
        }
        // Append publication bytes to relevant vector.
        vector::append(to_append_to_ref_mut, bytes);
    }

    /// Publish code from staging area.
    public entry fun publish_staged_code(
        publisher: &signer,
    ) acquires StagingArea {
        // Mutably borrow staging area.
        let staging_area_ref_mut =
            borrow_global_mut<StagingArea>(publisher_address);
        // Publish code.
        publish_package_txn(publisher, copy metadata, copy code);
        // Clear out staging area.
        staging_area_ref_mut.metadata_serialized = vector::empty();
        staging_area_ref_mut.code = vector::empty();
    }
}
```

**Comment by movekevin** [comment]
This is a good feature to have. Overall there are some pain points with the current module deployment and upgrade process, especially when there's a resource account involved. @alnoki Do you have any other pain points or suggestions beside this feature?

**Comment by wrwg** [comment]
Have not seen this issue when I created #6936 yesterday, which I think is a simpler and more flexible solution with the same effect. Closing this here, feel free to reopen.

**Comment by alnoki** [comment]
> This is a good feature to have. Overall there are some pain points with the current module deployment and upgrade process, especially when there's a resource account involved. @alnoki Do you have any other pain points or suggestions beside this feature?

@movekevin moving discussion to #6936 per @wrwg 's proposal

**Comment by wrwg** [comment]
Reopening as long as we are still discussing solutions.

**Comment by alnoki** [comment]
@wrwg @movekevin for reasons discussed in #6936 it appears that this issue is indeed separate from incremental publication. Mainly, this issue is related to publication that is simply not possible with the current schema. To summarize a few points:

1. Consider a 127k package with a 1k metadata file and three 42k modules. Ideally publication could be partitioned even within bytecode, so that only two transactions have to be submitted to publish the whole package.
2. Partitioning within bytecode may be necessary for modules that are larger than 64k: for example complex math libraries or package-in-a-modules (some devs may condense entire packages into a single module, in addition to inlined functions, to reduce function call gas as much as possible).
3. Staging a bytes vector on-chain has potentially messy implications, but this solution may be necessary. Perhaps in the case that staged package bytes fail to deploy, due to a failed bytecode verification, a staging area will simply be flushed?
4. The solution must support multisig deployment, whereby signatories sign off on two separate transactions (simply building in client-side functionality to the CLI, which assumes a local keyfile, may be insufficient).

**Comment by wrwg** [comment]
This is in our backlog and we will be getting to there.

**Comment by e99243506bigplay** [comment]
Please make these move function to be native one, otherwise these function when processing big vectors I think could be gas guzzlers.
https://github.com/aptos-labs/aptos-core/blob/d88fea64851b461d7b32acfb21bbb47deb717ed6/aptos-move/framework/move-stdlib/sources/vector.move#L67-L114

**Comment by davidiw** [comment]
Why not make this a move example and add some Python SDK code that supports it?

**Comment by davidiw** [comment]
We could then consider if it makes sense to generalize and support in the TS SDK and CLI + make part of the core framework....

**Comment by alnoki** [comment]
> Why not make this a move example and add some Python SDK code that supports it?



> We could then consider if it makes sense to generalize and support in the TS SDK and CLI + make part of the core framework....


Tagging @e99243506bigplay per https://github.com/aptos-labs/aptos-core/issues/6936#issuecomment-1522652110

**Comment by alnoki** [comment]
@movekevin 

Noting here it would be additionally useful for the staging area to be accessible by those other than the chunked stager. Use case:

1. Single-signer stager chunks 140k into a staging area across 3 transactions
2. 3-of-5 multisig votes to publish the staged code at the staging area

The total number of transactions here is 6 (3 stage txns, 3 multisig vote txns, 1 multisig invocation txn), versus 12 in the case of staging from the multisig itself (4 txns to vote and invoke each of 3 staging operations, with the final txn doing a combined stage and publication operation)

**Comment by davidiw** [comment]
https://github.com/aptos-labs/aptos-core/pull/9110/commits/e6bc02a3181d93dd9f5e355fd64eed49a71a17e5

It is currently live on testnet and verified: https://fullnode.testnet.aptoslabs.com/v1/accounts/0xfa3911d7715238b2e3bd5b26b6a35e11ffa16cff318bc11471e84eccee8bd291/modules

**Comment by alnoki** [comment]
> https://github.com/aptos-labs/aptos-core/commit/e6bc02a3181d93dd9f5e355fd64eed49a71a17e5
>
> It is currently live on testnet and verified: https://fullnode.testnet.aptoslabs.com/v1/accounts/0xfa3911d7715238b2e3bd5b26b6a35e11ffa16cff318bc11471e84eccee8bd291/modules

@davidiw nice, the `publish_staged_code()` function looks like it addresses https://github.com/aptos-labs/aptos-core/issues/6905#issuecomment-1636905557

One useful feature to add here would be the ability to verify staged code against locally-compiled source

**Comment by e99243506bigplay** [comment]
Sorry but, that wasn't what I looking for. Sure it allow you to upload a package be larger than ~64kb, but its not a module be larger than ~64kb, the module upload size is still limited by transaction request max size AFAIK I see on the example code there.

**Comment by davidiw** [comment]
> Sorry but, that wasn't what I looking for. Sure it allow you to upload a package be larger than ~64kb, but its not a module be larger than ~64kb, the module upload size is still limited by transaction request max size at that AFAIK I see on the example code there.
> 
> I have use case on very big module that basically all function is inlined and without nearly non necessary function call and inline overhead, every function is treated be a "kernel" or an "action" to extremely optimize out the execution gas fee.
> 
> Because global resource access is strictly limited to in current module, so this module has be very very big if want the module features rich if try to manipulated module related resources if want to achieve optimize execution gas fee to perfect state.
> 
> That is a trade to about sacrifice execution code space cost for extremely optimized execution gas fee.

Do you want to share a pointer?

**Comment by e99243506bigplay** [comment]
> > Sorry but, that wasn't what I looking for. Sure it allow you to upload a package be larger than ~64kb, but its not a module be larger than ~64kb, the module upload size is still limited by transaction request max size at that AFAIK I see on the example code there.
> > I have use case on very big module that basically all function is inlined and without nearly non necessary function call and inline overhead, every function is treated be a "kernel" or an "action" to extremely optimize out the execution gas fee.
> > Because global resource access is strictly limited to in current module, so this module has be very very big if want the module features rich if try to manipulated module related resources if want to achieve optimize execution gas fee to perfect state.
> > That is a trade to about sacrifice execution code space cost for extremely optimized execution gas fee.
> 
> Do you want to share a pointer?

There is no such of pointer concept in move language, what is the point to ask this?

**Comment by davidiw** [comment]
> There is no such of pointer concept in move language, what is the point to ask this?

This wasn't a question about Move. This was an ask to please point me to your application so that I can better understand how or why a module gets to 64K sizes.

**Comment by movekevin** [comment]
One of the key distinctions that Aptos does well is to allow developers to build without having to think too much about gas. This makes development in Move much more natural and almost as rich as building a normal application off chain. I think it makes more sense to continue this direction and make it even more delightful and easier to develop in Move. It's not about optimizing gas, but more about the ability to build bigger applications without running into the transaction size limit. Currently, developers have to do so adhoc by accumulating bytes on chain; this issue aims to make this more standard and easier. Building large rich applications should be easy without developers to build a lot of infrastructure and tooling manually to do so.

**Comment by e99243506bigplay** [comment]
> > There is no such of pointer concept in move language, what is the point to ask this?
> 
> This wasn't a question about Move. This was an ask to please point me to your application so that I can better understand how or why a module gets to 64K sizes.

Very well, as you know, I am doing arbitrage on Aptos Ecosystem, There is some DEX there, to arbitrage, I have to specify the route, because there is none of custom goto or function pointer on Move Language, and I dont want to use if branch, so I have to generate tons of functions as arbitrage route to ensure any route has the lowest execution fee for myself.

```
pub enum LP {
    StarSwap,
    AnimeSwap,
    PancakeSwap,
    LiquidSwap,
    Aux,
    CetusAMM,
    JujubeSwap,
    AptoSwap,
    BaptSwap,
}
```
2 route arbitrage from 0 to 9, will be like:
```
x0::z0z1, x0::z0z2, x0::z0z3, x0::z0z4, x0::z0z5, x0::z0z6, x0::z0z7, x0::z0z8, x0::z1z0, x0::z1z2, x0::z1z3, x0::z1z4, x0::z1z5, x0::z1z6, x0::z1z7, x0::z1z8, x0::z2z0, x0::z2z1, x0::z2z3, x0::z2z4, x0::z2z5, x0::z2z6, x0::z2z7, x0::z2z8, x0::z3z0, x0::z3z1, x0::z3z2, x0::z3z4, x0::z3z5, x0::z3z6, x0::z3z7, x0::z3z8, x0::z4z0, x0::z4z1, x0::z4z2, x0::z4z3, x0::z4z5, x0::z4z6, x0::z4z7, x0::z4z8, x0::z5z0, x0::z5z1, x0::z5z2, x0::z5z3, x0::z5z4, x0::z5z6, x0::z5z7, x0::z5z8, x0::z6z0, x0::z6z1, x0::z6z2, x0::z6z3, x0::z6z4, x0::z6z5, x0::z6z7, x0::z6z8, x0::z7z0, x0::z7z1, x0::z7z2, x0::z7z3, x0::z7z4, x0::z7z5, x0::z7z6, x0::z7z8, x0::z8z0, x0::z8z1, x0::z8z2, x0::z8z3, x0::z8z4, x0::z8z5, x0::z8z6, x0::z8z7
```
<details>
  <summary>if I going to expand to 3 route arbitrage will be:</summary>
x0::z0z0z0, x0::z0z0z1, x0::z0z0z2, x0::z0z0z3, x0::z0z0z4, x0::z0z0z5, x0::z0z0z6, x0::z0z0z7, x0::z0z0z8, x0::z0z1z0, x0::z0z1z1, x0::z0z1z2, x0::z0z1z3, x0::z0z1z4, x0::z0z1z5, x0::z0z1z6, x0::z0z1z7, x0::z0z1z8, x0::z0z2z0, x0::z0z2z1, x0::z0z2z2, x0::z0z2z3, x0::z0z2z4, x0::z0z2z5, x0::z0z2z6, x0::z0z2z7, x0::z0z2z8, x0::z0z3z0, x0::z0z3z1, x0::z0z3z2, x0::z0z3z3, x0::z0z3z4, x0::z0z3z5, x0::z0z3z6, x0::z0z3z7, x0::z0z3z8, x0::z0z4z0, x0::z0z4z1, x0::z0z4z2, x0::z0z4z3, x0::z0z4z4, x0::z0z4z5, x0::z0z4z6, x0::z0z4z7, x0::z0z4z8, x0::z0z5z0, x0::z0z5z1, x0::z0z5z2, x0::z0z5z3, x0::z0z5z4, x0::z0z5z5, x0::z0z5z6, x0::z0z5z7, x0::z0z5z8, x0::z0z6z0, x0::z0z6z1, x0::z0z6z2, x0::z0z6z3, x0::z0z6z4, x0::z0z6z5, x0::z0z6z6, x0::z0z6z7, x0::z0z6z8, x0::z0z7z0, x0::z0z7z1, x0::z0z7z2, x0::z0z7z3, x0::z0z7z4, x0::z0z7z5, x0::z0z7z6, x0::z0z7z7, x0::z0z7z8, x0::z0z8z0, x0::z0z8z1, x0::z0z8z2, x0::z0z8z3, x0::z0z8z4, x0::z0z8z5, x0::z0z8z6, x0::z0z8z7, x0::z0z8z8, x0::z1z0z0, x0::z1z0z1, x0::z1z0z2, x0::z1z0z3, x0::z1z0z4, x0::z1z0z5, x0::z1z0z6, x0::z1z0z7, x0::z1z0z8, x0::z1z1z0, x0::z1z1z1, x0::z1z1z2, x0::z1z1z3, x0::z1z1z4, x0::z1z1z5, x0::z1z1z6, x0::z1z1z7, x0::z1z1z8, x0::z1z2z0, x0::z1z2z1, x0::z1z2z2, x0::z1z2z3, x0::z1z2z4, x0::z1z2z5, x0::z1z2z6, x0::z1z2z7, x0::z1z2z8, x0::z1z3z0, x0::z1z3z1, x0::z1z3z2, x0::z1z3z3, x0::z1z3z4, x0::z1z3z5, x0::z1z3z6, x0::z1z3z7, x0::z1z3z8, x0::z1z4z0, x0::z1z4z1, x0::z1z4z2, x0::z1z4z3, x0::z1z4z4, x0::z1z4z5, x0::z1z4z6, x0::z1z4z7, x0::z1z4z8, x0::z1z5z0, x0::z1z5z1, x0::z1z5z2, x0::z1z5z3, x0::z1z5z4, x0::z1z5z5, x0::z1z5z6, x0::z1z5z7, x0::z1z5z8, x0::z1z6z0, x0::z1z6z1, x0::z1z6z2, x0::z1z6z3, x0::z1z6z4, x0::z1z6z5, x0::z1z6z6, x0::z1z6z7, x0::z1z6z8, x0::z1z7z0, x0::z1z7z1, x0::z1z7z2, x0::z1z7z3, x0::z1z7z4, x0::z1z7z5, x0::z1z7z6, x0::z1z7z7, x0::z1z7z8, x0::z1z8z0, x0::z1z8z1, x0::z1z8z2, x0::z1z8z3, x0::z1z8z4, x0::z1z8z5, x0::z1z8z6, x0::z1z8z7, x0::z1z8z8, x0::z2z0z0, x0::z2z0z1, x0::z2z0z2, x0::z2z0z3, x0::z2z0z4, x0::z2z0z5, x0::z2z0z6, x0::z2z0z7, x0::z2z0z8, x0::z2z1z0, x0::z2z1z1, x0::z2z1z2, x0::z2z1z3, x0::z2z1z4, x0::z2z1z5, x0::z2z1z6, x0::z2z1z7, x0::z2z1z8, x0::z2z2z0, x0::z2z2z1, x0::z2z2z2, x0::z2z2z3, x0::z2z2z4, x0::z2z2z5, x0::z2z2z6, x0::z2z2z7, x0::z2z2z8, x0::z2z3z0, x0::z2z3z1, x0::z2z3z2, x0::z2z3z3, x0::z2z3z4, x0::z2z3z5, x0::z2z3z6, x0::z2z3z7, x0::z2z3z8, x0::z2z4z0, x0::z2z4z1, x0::z2z4z2, x0::z2z4z3, x0::z2z4z4, x0::z2z4z5, x0::z2z4z6, x0::z2z4z7, x0::z2z4z8, x0::z2z5z0, x0::z2z5z1, x0::z2z5z2, x0::z2z5z3, x0::z2z5z4, x0::z2z5z5, x0::z2z5z6, x0::z2z5z7, x0::z2z5z8, x0::z2z6z0, x0::z2z6z1, x0::z2z6z2, x0::z2z6z3, x0::z2z6z4, x0::z2z6z5, x0::z2z6z6, x0::z2z6z7, x0::z2z6z8, x0::z2z7z0, x0::z2z7z1, x0::z2z7z2, x0::z2z7z3, x0::z2z7z4, x0::z2z7z5, x0::z2z7z6, x0::z2z7z7, x0::z2z7z8, x0::z2z8z0, x0::z2z8z1, x0::z2z8z2, x0::z2z8z3, x0::z2z8z4, x0::z2z8z5, x0::z2z8z6, x0::z2z8z7, x0::z2z8z8, x0::z3z0z0, x0::z3z0z1, x0::z3z0z2, x0::z3z0z3, x0::z3z0z4, x0::z3z0z5, x0::z3z0z6, x0::z3z0z7, x0::z3z0z8, x0::z3z1z0, x0::z3z1z1, x0::z3z1z2, x0::z3z1z3, x0::z3z1z4, x0::z3z1z5, x0::z3z1z6, x0::z3z1z7, x0::z3z1z8, x0::z3z2z0, x0::z3z2z1, x0::z3z2z2, x0::z3z2z3, x0::z3z2z4, x0::z3z2z5, x0::z3z2z6, x0::z3z2z7, x0::z3z2z8, x0::z3z3z0, x0::z3z3z1, x0::z3z3z2, x0::z3z3z3, x0::z3z3z4, x0::z3z3z5, x0::z3z3z6, x0::z3z3z7, x0::z3z3z8, x0::z3z4z0, x0::z3z4z1, x0::z3z4z2, x0::z3z4z3, x0::z3z4z4, x0::z3z4z5, x0::z3z4z6, x0::z3z4z7, x0::z3z4z8, x0::z3z5z0, x0::z3z5z1, x0::z3z5z2, x0::z3z5z3, x0::z3z5z4, x0::z3z5z5, x0::z3z5z6, x0::z3z5z7, x0::z3z5z8, x0::z3z6z0, x0::z3z6z1, x0::z3z6z2, x0::z3z6z3, x0::z3z6z4, x0::z3z6z5, x0::z3z6z6, x0::z3z6z7, x0::z3z6z8, x0::z3z7z0, x0::z3z7z1, x0::z3z7z2, x0::z3z7z3, x0::z3z7z4, x0::z3z7z5, x0::z3z7z6, x0::z3z7z7, x0::z3z7z8, x0::z3z8z0, x0::z3z8z1, x0::z3z8z2, x0::z3z8z3, x0::z3z8z4, x0::z3z8z5, x0::z3z8z6, x0::z3z8z7, x0::z3z8z8, x0::z4z0z0, x0::z4z0z1, x0::z4z0z2, x0::z4z0z3, x0::z4z0z4, x0::z4z0z5, x0::z4z0z6, x0::z4z0z7, x0::z4z0z8, x0::z4z1z0, x0::z4z1z1, x0::z4z1z2, x0::z4z1z3, x0::z4z1z4, x0::z4z1z5, x0::z4z1z6, x0::z4z1z7, x0::z4z1z8, x0::z4z2z0, x0::z4z2z1, x0::z4z2z2, x0::z4z2z3, x0::z4z2z4, x0::z4z2z5, x0::z4z2z6, x0::z4z2z7, x0::z4z2z8, x0::z4z3z0, x0::z4z3z1, x0::z4z3z2, x0::z4z3z3, x0::z4z3z4, x0::z4z3z5, x0::z4z3z6, x0::z4z3z7, x0::z4z3z8, x0::z4z4z0, x0::z4z4z1, x0::z4z4z2, x0::z4z4z3, x0::z4z4z4, x0::z4z4z5, x0::z4z4z6, x0::z4z4z7, x0::z4z4z8, x0::z4z5z0, x0::z4z5z1, x0::z4z5z2, x0::z4z5z3, x0::z4z5z4, x0::z4z5z5, x0::z4z5z6, x0::z4z5z7, x0::z4z5z8, x0::z4z6z0, x0::z4z6z1, x0::z4z6z2, x0::z4z6z3, x0::z4z6z4, x0::z4z6z5, x0::z4z6z6, x0::z4z6z7, x0::z4z6z8, x0::z4z7z0, x0::z4z7z1, x0::z4z7z2, x0::z4z7z3, x0::z4z7z4, x0::z4z7z5, x0::z4z7z6, x0::z4z7z7, x0::z4z7z8, x0::z4z8z0, x0::z4z8z1, x0::z4z8z2, x0::z4z8z3, x0::z4z8z4, x0::z4z8z5, x0::z4z8z6, x0::z4z8z7, x0::z4z8z8, x0::z5z0z0, x0::z5z0z1, x0::z5z0z2, x0::z5z0z3, x0::z5z0z4, x0::z5z0z5, x0::z5z0z6, x0::z5z0z7, x0::z5z0z8, x0::z5z1z0, x0::z5z1z1, x0::z5z1z2, x0::z5z1z3, x0::z5z1z4, x0::z5z1z5, x0::z5z1z6, x0::z5z1z7, x0::z5z1z8, x0::z5z2z0, x0::z5z2z1, x0::z5z2z2, x0::z5z2z3, x0::z5z2z4, x0::z5z2z5, x0::z5z2z6, x0::z5z2z7, x0::z5z2z8, x0::z5z3z0, x0::z5z3z1, x0::z5z3z2, x0::z5z3z3, x0::z5z3z4, x0::z5z3z5, x0::z5z3z6, x0::z5z3z7, x0::z5z3z8, x0::z5z4z0, x0::z5z4z1, x0::z5z4z2, x0::z5z4z3, x0::z5z4z4, x0::z5z4z5, x0::z5z4z6, x0::z5z4z7, x0::z5z4z8, x0::z5z5z0, x0::z5z5z1, x0::z5z5z2, x0::z5z5z3, x0::z5z5z4, x0::z5z5z5, x0::z5z5z6, x0::z5z5z7, x0::z5z5z8, x0::z5z6z0, x0::z5z6z1, x0::z5z6z2, x0::z5z6z3, x0::z5z6z4, x0::z5z6z5, x0::z5z6z6, x0::z5z6z7, x0::z5z6z8, x0::z5z7z0, x0::z5z7z1, x0::z5z7z2, x0::z5z7z3, x0::z5z7z4, x0::z5z7z5, x0::z5z7z6, x0::z5z7z7, x0::z5z7z8, x0::z5z8z0, x0::z5z8z1, x0::z5z8z2, x0::z5z8z3, x0::z5z8z4, x0::z5z8z5, x0::z5z8z6, x0::z5z8z7, x0::z5z8z8, x0::z6z0z0, x0::z6z0z1, x0::z6z0z2, x0::z6z0z3, x0::z6z0z4, x0::z6z0z5, x0::z6z0z6, x0::z6z0z7, x0::z6z0z8, x0::z6z1z0, x0::z6z1z1, x0::z6z1z2, x0::z6z1z3, x0::z6z1z4, x0::z6z1z5, x0::z6z1z6, x0::z6z1z7, x0::z6z1z8, x0::z6z2z0, x0::z6z2z1, x0::z6z2z2, x0::z6z2z3, x0::z6z2z4, x0::z6z2z5, x0::z6z2z6, x0::z6z2z7, x0::z6z2z8, x0::z6z3z0, x0::z6z3z1, x0::z6z3z2, x0::z6z3z3, x0::z6z3z4, x0::z6z3z5, x0::z6z3z6, x0::z6z3z7, x0::z6z3z8, x0::z6z4z0, x0::z6z4z1, x0::z6z4z2, x0::z6z4z3, x0::z6z4z4, x0::z6z4z5, x0::z6z4z6, x0::z6z4z7, x0::z6z4z8, x0::z6z5z0, x0::z6z5z1, x0::z6z5z2, x0::z6z5z3, x0::z6z5z4, x0::z6z5z5, x0::z6z5z6, x0::z6z5z7, x0::z6z5z8, x0::z6z6z0, x0::z6z6z1, x0::z6z6z2, x0::z6z6z3, x0::z6z6z4, x0::z6z6z5, x0::z6z6z6, x0::z6z6z7, x0::z6z6z8, x0::z6z7z0, x0::z6z7z1, x0::z6z7z2, x0::z6z7z3, x0::z6z7z4, x0::z6z7z5, x0::z6z7z6, x0::z6z7z7, x0::z6z7z8, x0::z6z8z0, x0::z6z8z1, x0::z6z8z2, x0::z6z8z3, x0::z6z8z4, x0::z6z8z5, x0::z6z8z6, x0::z6z8z7, x0::z6z8z8, x0::z7z0z0, x0::z7z0z1, x0::z7z0z2, x0::z7z0z3, x0::z7z0z4, x0::z7z0z5, x0::z7z0z6, x0::z7z0z7, x0::z7z0z8, x0::z7z1z0, x0::z7z1z1, x0::z7z1z2, x0::z7z1z3, x0::z7z1z4, x0::z7z1z5, x0::z7z1z6, x0::z7z1z7, x0::z7z1z8, x0::z7z2z0, x0::z7z2z1, x0::z7z2z2, x0::z7z2z3, x0::z7z2z4, x0::z7z2z5, x0::z7z2z6, x0::z7z2z7, x0::z7z2z8, x0::z7z3z0, x0::z7z3z1, x0::z7z3z2, x0::z7z3z3, x0::z7z3z4, x0::z7z3z5, x0::z7z3z6, x0::z7z3z7, x0::z7z3z8, x0::z7z4z0, x0::z7z4z1, x0::z7z4z2, x0::z7z4z3, x0::z7z4z4, x0::z7z4z5, x0::z7z4z6, x0::z7z4z7, x0::z7z4z8, x0::z7z5z0, x0::z7z5z1, x0::z7z5z2, x0::z7z5z3, x0::z7z5z4, x0::z7z5z5, x0::z7z5z6, x0::z7z5z7, x0::z7z5z8, x0::z7z6z0, x0::z7z6z1, x0::z7z6z2, x0::z7z6z3, x0::z7z6z4, x0::z7z6z5, x0::z7z6z6, x0::z7z6z7, x0::z7z6z8, x0::z7z7z0, x0::z7z7z1, x0::z7z7z2, x0::z7z7z3, x0::z7z7z4, x0::z7z7z5, x0::z7z7z6, x0::z7z7z7, x0::z7z7z8, x0::z7z8z0, x0::z7z8z1, x0::z7z8z2, x0::z7z8z3, x0::z7z8z4, x0::z7z8z5, x0::z7z8z6, x0::z7z8z7, x0::z7z8z8, x0::z8z0z0, x0::z8z0z1, x0::z8z0z2, x0::z8z0z3, x0::z8z0z4, x0::z8z0z5, x0::z8z0z6, x0::z8z0z7, x0::z8z0z8, x0::z8z1z0, x0::z8z1z1, x0::z8z1z2, x0::z8z1z3, x0::z8z1z4, x0::z8z1z5, x0::z8z1z6, x0::z8z1z7, x0::z8z1z8, x0::z8z2z0, x0::z8z2z1, x0::z8z2z2, x0::z8z2z3, x0::z8z2z4, x0::z8z2z5, x0::z8z2z6, x0::z8z2z7, x0::z8z2z8, x0::z8z3z0, x0::z8z3z1, x0::z8z3z2, x0::z8z3z3, x0::z8z3z4, x0::z8z3z5, x0::z8z3z6, x0::z8z3z7, x0::z8z3z8, x0::z8z4z0, x0::z8z4z1, x0::z8z4z2, x0::z8z4z3, x0::z8z4z4, x0::z8z4z5, x0::z8z4z6, x0::z8z4z7, x0::z8z4z8, x0::z8z5z0, x0::z8z5z1, x0::z8z5z2, x0::z8z5z3, x0::z8z5z4, x0::z8z5z5, x0::z8z5z6, x0::z8z5z7, x0::z8z5z8, x0::z8z6z0, x0::z8z6z1, x0::z8z6z2, x0::z8z6z3, x0::z8z6z4, x0::z8z6z5, x0::z8z6z6, x0::z8z6z7, x0::z8z6z8, x0::z8z7z0, x0::z8z7z1, x0::z8z7z2, x0::z8z7z3, x0::z8z7z4, x0::z8z7z5, x0::z8z7z6, x0::z8z7z7, x0::z8z7z8, x0::z8z8z0, x0::z8z8z1, x0::z8z8z2, x0::z8z8z3, x0::z8z8z4, x0::z8z8z5, x0::z8z8z6, x0::z8z8z7, x0::z8z8z8
</details>

Because I try to don't use if branch, so I choose to use off chain program to select an move function to replace if branch to do arbitrage.

**Comment by davidiw** [comment]
@e99243506bigplay, how much are you saving in total gas costs? Isn't like 100s of octa?

**Comment by e99243506bigplay** [comment]
> @e99243506bigplay, how much are you saving in total gas costs? Isn't like 100s of octa?

Look, there is 100 APT arbitrage reward, every arbitrager want it, so they using "gas unit price" to bidding the reward, who using highest "gas unit price" than other arbitrager, then that who wins the reward, by this cost he may cost total 10APT on it, that is why less execution gas fee is better.
But now, gas priority mechanism look are not working like that so I don't know, it works on past version of gas priority.

**Comment by davidiw** [comment]
We did it... https://github.com/aptos-labs/aptos-core/pull/9712

This contract is on testnet and mainnet and easily deployable. There's a lightweight Python cli to use it, while the team figures out Rust CLI support.

Have at it.

**Comment by e99243506bigplay** [comment]
> We did it... #9712
> 
> This contract is on testnet and mainnet and easily deployable. There's a lightweight Python cli to use it, while the team figures out Rust CLI support.
> 
> Have at it.

Thanks your first implement, although that looks like is not optimized very well, but still, good job.
if I do, I will need move assemble language to do it, so I possibly to make vec unpack and pack process in stack.

**Comment by e99243506bigplay** [comment]
> We did it... #9712
> 
> This contract is on testnet and mainnet and easily deployable. There's a lightweight Python cli to use it, while the team figures out Rust CLI support.
> 
> Have at it.

No, this non optimized version of large package uploader is drained my 2 APTs for uploading 700k move contract package. Well I better doing the Move Assembly Language stuff.

**Comment by mshakeg** [comment]
Hey @davidiw @gregnazario `--chunked-publish` seems to only work when publishing a package under an object(with `aptos move deploy-object`) and not when when publishing under a resource account(with `aptos move create-resource-account-and-publish-package`), can this be fixed?
