### ISSUE TITLE
[Feature Request] default --package-dir for CLI

### ISSUE THREAD

**Issue by magnum6actual** [aptos-labs/aptos-core#726]
# 🚀 Feature Request

The CLI is great - very helpful tool. I'm finding that I'm constantly typing "--package-dir sources" for all "aptos move" commands.  It would be great to either default the package directory to 'sources' if the option isn't provided.  Or, perhaps more cleanly, there could be an entry in the Move.toml [package] options that points to the source path like:

```
[package]
name = "Examples"
version = "0.0.0"
package_dir = "./sources"
```

**Comment by gregnazario** [comment]
Ah, you actually don't have to type `sources` you could also put `.`.

This has been solved though, and now it defaults to . https://github.com/aptos-labs/aptos-core/commit/29e6be2fac8a773592ebee555f8cd9acf52daa81

We'll likely have to improve this for windows development in the future, since we know the CLI doesn't really work on windows at this moment.

**Comment by gregnazario** [comment]
Actually, are you asking for having a list of project names or something like that in the aptos CLI config?

**Comment by magnum6actual** [comment]
No - defaulting to `.` is all I needed.
