### ISSUE TITLE
[DevEx RFC][TS-SDK] Add support for compound `TypeTag`

### ISSUE THREAD

**Issue by JackyWYX** [aptos-labs/aptos-core#7575]
## Motivation

Currently, compound / nested type argument is not allowed in Aptos TS-SDK. E.g. 

```
0x5a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948::lp_coin::LP<0xf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa::asset::USDC, 0x1::aptos_coin::AptosCoin, 0x190d44266241744264b964a37b8f09863167a12d3e70cda39376cfb4e3561e12::curves::Uncorrelated>
```

The given structure is a LP coin type for Pontem liquidity token. The structure is not able to be called in TS-SDK for coin register / transfer. 

## Proposals

Implement the nested TypeTag for compound structure. 

```
// aptos/src/aptos_types/type_tag.ts
export class StructTag {
    ...
    static fromString(structTag: string): StructTag {
    // Type args are not supported in string literal
    if (structTag.includes("<")) {
      throw new Error("Not implemented");
    }
```

**Comment by wjw12** [comment]
Please prioritize this issue as it's blocking many operations involving LP token types

**Comment by gregnazario** [comment]
So summary of the issue here:
* TS SDK doesn't support nested struct tags with generics e.g. (0x1::coin::Coin<0x1::module::Struct<0x2::coin::MyCoin>>)
* Parsing doesn't currently handle this


Items that need to be done:
* Parse the three pieces of the function e.g. `0x1::coin::Coin` into `0x1, coin, Coin`
* Parse any associated generic types accordingly at a top level e.g. `0x1::coin::Coin<0x2::coin::MyCoin, 0x1::module::Struct<0x2::coin::MyCoin>>` into `0x2::coin::MyCoin, 0x1::module::Struct<0x2::coin::MyCoin>`

**Comment by borispovod** [comment]
👍

**Comment by 0xjinn** [comment]
Hi @JackyWYX , may I ask what methods you invoke to create the transaction, or how you create the transaction?

Specifically, curious if you done in this approach, or similar?

```
const rawTxn = await aptosClient.generateTransaction(my_address, {
      function: "0x1::managed_coin::register",
      type_arguments: [`0x1:🪙:Coin<0x1::module::Struct<0x2:🪙:MyCoin>>`],
      arguments: [],
    });
```
