### ISSUE TITLE
[Bug] aptos-stdlib dependency in compiler 

### ISSUE THREAD

**Issue by sausagee** [aptos-labs/aptos-core#9165]
# 🐛 Bug
Compilation fails if an application and its dependencies import aptos-stdlib without this address (`aptos_framework = "0x1"`) set.

## To reproduce
See https://github.com/aptos-labs/aptos-core/pull/9142

**Stack trace/error message**
```
"Error": "Move compilation failed: Unable to resolve packages for
package 'Tsunami': While resolving dependency 'Switchboard' in package 'Tsunami': Unable to resolve package depen
dency 'Switchboard': While resolving dependency 'AptosStdlib' in package 'Switchboard': Unable to resolve package dependency 'AptosStdlib': Conflicting dependencies found: package '
AptosStdlib' conflicts with 'AptosStdlib'"
```

**Comment by brmataptos** [comment]
I think this bug refers to the client application case.  Maybe try changing something in aptos-move/move-examples/...

**Comment by aalok-t** [comment]
Unable to reproduce the bug. 

For instance, consider [aptos-move/framework/aptos-framework](https://github.com/aptos-labs/aptos-core/blob/2ea28a76d5761ff5e862edf5018c9712dc809f14/aptos-move/framework/aptos-framework/Move.toml) where the address aptos_framework = “0x1” occurs. Removing it would cause a compilation error (as it should) because files like [aptos-framework/sources/configs/execution_config.move](https://github.com/aptos-labs/aptos-core/blob/2ea28a76d5761ff5e862edf5018c9712dc809f14/aptos-move/framework/aptos-framework/sources/configs/execution_config.move#L3) require it. A number of files such as [aptos-move/framework/aptos-token/Move.toml](https://github.com/aptos-labs/aptos-core/blob/2ea28a76d5761ff5e862edf5018c9712dc809f14/aptos-move/framework/aptos-token/Move.toml) use this address unnecessarily and removing it caused no compilation errors.
