### ISSUE TITLE
[Bug] Txn 192831665 in mainnet is suspect to violated gas priority, Please check block 72197507 of txns.

### ISSUE THREAD

**Issue by e99243506bigplay** [aptos-labs/aptos-core#9245]
# 🐛 Bug

Txn 192831669 and 192831666 is paid much more gas unit fee than 192831665 in same block.

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```

## Expected Behavior

Highest gas unit prices bidder be come first place.

## System information

**Please complete the following information:**
- 
- 
-

**Comment by e99243506bigplay** [comment]
Oh no... Please check block 72203248 and 72203937. Gas priority looks like is broken now.

**Comment by davidiw** [comment]
There's limitations to gas priority:
* Priority is loosely assigned and if there's no contention, there's really no guarantees about the outcomes.
* BlockSTM executes up to 8 transactions parallel hence if there's no contention two transactions of different priority can execute together.
* Ordering is assigned after execution.
* Higher gas ensures higher likelihood of being included in a block not precisely the order in that block.

I think there's an interesting aspect here in that if two transactions are competing for a shared resource, paying a slightly higher gas price may be insufficient to win. You may need to squeeze the other transaction out of the block, which is non-trivial considering that the transactions in the block are chosen in round robin fashion and contain up to thousands of transactions.

Let me also share this upstream with the team, but at this point in time there doesn't seem to be anything here. Even a block with 64 transactions or more where there might be misordering wouldn't be sufficient, because consider the case where I have 62 non-conflicting transactions paying a gas price of 100 and 2 paying 800. The 62 will all execute in parallel and be happy whereas the last 2 will need to be rescheduled sequentially. They may be the last two transactions in the block.

**Comment by davidiw** [comment]
Going to close out this issue and created this one: https://github.com/aptos-labs/aptos-core/issues/9247
