### ISSUE TITLE
[Bug] [compiler-v2] tests for compiler output comparison should pull sources from v1 test dirs

### ISSUE THREAD

**Issue by brmataptos** [aptos-labs/aptos-core#9627]
# 🐛 Bug

Many of the compiler-v2 tests (both transactional and not) use a copy of the .move files.  These should instead be using the original tests to facilitate comparison and reduce risk of accidental degradation of tests.

**Comment by wrwg** [comment]
This tests have intentionally been copied because (a) eventually the v2 compiler will be removed. Then these tests still make sense to run not in comparison mode (b) the tests are incrementally ported. There is a large number of tests which aren't make any sense yet because the features (safety analysis e.g.) aren't yet implemented. 

It is no big deal to compare the directory contents if one wants to reason about which tests have been ported so far.
